### PR TITLE
Undirected mutation behaviour when `queryDirection` is `UNDIRECTED`

### LINKED ISSUE #2046: Disconnect for undirected relationships doesn't work from both sides
**Describe the bug**
Disconnecting undirected relationships only works from one side

**Type definitions**
````graphql
type Item {
  name: String
  relatesTo: [Item!]! @relationship(type: "RELATES_TO", direction: OUT, queryDirection: DEFAULT_UNDIRECTED)
}
````

**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation...
````graphql
mutation {
  createItems(input: {
    name: "A",
    relatesTo: {
      create: {
        node: {
          name: "B"
        }
      }
    }
  }) {
    items {
      name
      relatesTo {
        name
      }
    }
  }
}
````
3. Then run the following Query...
The relationship was created successfully. It is possible to query the relationship from both sides.
````graphql
query {
  items {
    name
    relatesTo {
      name
      relatesTo {
        name
      }
    }
  }
}
````
Result:
````json
{
  "data": {
    "items": [
      {
        "name": "A",
        "relatesTo": [
          {
            "name": "B",
            "relatesTo": [
              {
                "name": "A"
              }
            ]
          }
        ]
      },
      {
        "name": "B",
        "relatesTo": [
          {
            "name": "A",
            "relatesTo": [
              {
                "name": "B"
              }
            ]
          }
        ]
      }
    ]
  }
}
````
4. Run the following mutations:
(1) Works fine:
The relationship has been deleted
````graphql
mutation {
  updateItems(
    where: {
  		name: "A",
    },
    disconnect: {
      relatesTo: {
        where: {
          node: {
            name: "B"
          }
        }
      }
    }
  ) {
    items {
      name
      relatesTo {
        name
        relatesTo {
          name
        }
      }
    }
  }
}
````
(2) Doesn't work:
The relationship persists after the mutation. Nothing has happened.
````graphql
mutation {
  updateItems(
    where: {
  		name: "B",
    },
    disconnect: {
      relatesTo: {
        where: {
          node: {
            name: "A"
          }
        }
      }
    }
  ) {
    items {
      name
      relatesTo {
        name
        relatesTo {
          name
        }
      }
    }
  }
}
````

**Expected behavior**
As with the query, a mutation should also work in both directions if the DEFAULT_UNDIRECTED or UNDIRECTED_ONLY option is activated.

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

Nested mutation operations now follow the relationship direction behaviour defined in `queryDirection`.

## Complexity

Complexity: Low

# Issue

Closes #2046

### CODE REVIEW

File: packages/graphql/src/translate/create-update-and-params.ts [hunk 1]
```diff
@@ -117,8 +118,16 @@ export default function createUpdateAndParams({
                 refNodes.push(context.nodes.find((x) => x.name === relationField.typeMeta.name) as Node);
             }
 
-            const inStr = relationField.direction === "IN" ? "<-" : "-";
-            const outStr = relationField.direction === "OUT" ? "->" : "-";
+            const inStr =
```
Comment (MacondoExpress) [inline packages/graphql/src/translate/create-update-and-params.ts]: I've noticed this logic to infer the direction is duplicated, we could write an utility to harmonize the behaviour and avoid inconsistencies. I'm thinking at a function that take relationField as input and returns an object with `inStr` and `outStr`

**Review by MacondoExpress — APPROVED** [review]

**Review by MacondoExpress — APPROVED** [review]
