### PR TITLE
Reintroduce camelcase for generating field names

### LINKED ISSUE #1038: Camel casing of type plural name is not behaving as before v3
**Describe the regression**

We are trying to upgrade our systems to use v3 of this library and we are getting errors related to how type plural names are being camel cased. For example before version 3 `AWSAccount` type type was pluralised and camel cased as  `awsAccounts` but after upgrading to v3 it is now camel cased as `aWSAccounts` and we are getting the following error
```
"Cannot query field \"awsAccounts\" on type \"Query\". Did you mean \"aWSAccounts\"?"
```
we use [camelcase](https://github.com/sindresorhus/camelcase#readme) library to do the conversion on our side which used to work perfectly before V3.

**Last working version**

Worked up to version: @neo4j/graphql@2.5.5

Stopped working in version: @neo4j/graphql@3.0.0

**Type definitions**
```
type AWSAccount {
    code: String
    accountName: String
}

type DNSZone {
    awsId: String
    zoneType: String
}

```
**To Reproduce**
 Run the following query
```
{
  awsAccounts {
    code
  }
}
```
**Expected behavior**
We expect to get list of AWS accounts' code
```
{
  "data": {
    "awsAccounts": [
      {
        "code": "387243903490"
      },
      {
        "code": "295479174736"
      },
      ... ]
      }
  }    
```

**System (please complete the following information):**

-   OS: macOS
-   Node.js version: 14.16.1

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

We made some glaring oversights in how we generate plural strings of type names in 3.0.0. This PR attempts to rationalise that behaviour, and add more tests.

# Issue

Closes #1038

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-graphql-docs-1040.surge.sh

File: packages/graphql/src/classes/Node.ts [hunk 1]
```diff
@@ -119,6 +134,19 @@ class Node extends GraphElement {
...
         this.queryOptions = input.queryOptionsDirective;
+        this.plural = this.generatePlural();
+    }
+
+    private generatePlural(): string {
+        const name = this.nodeDirective?.plural || this.name;
+
+        const re = /^(_+).+/;
+        const match = re.exec(name);
+        const leadingUnderscores = match?.[1] || "";
```
Comment (angrykoala) [inline packages/graphql/src/classes/Node.ts:145]: **suggestion (non-blocking)** Consider changing the regex so it always return a valid string with the leading underscores, to remove an extra check:

```suggestion
        const re = /^(_*).+/;
        const match = re.exec(name);
        const leadingUnderscores = match[1];
```

This way, if it doesn't match, it will return a match with an empty string

File: packages/graphql/src/classes/Node.ts [hunk 2]
```diff
@@ -158,9 +186,29 @@ class Node extends GraphElement {
         return this.constrainableFields.filter((field) => field.unique);
     }
 
-    public get plural(): string {
-        const pluralValue = this.nodeDirective?.plural ? this.nodeDirective.plural : pluralize(this.name);
-        return lowerFirst(pluralValue);
+    public get rootTypeFieldNames(): RootTypeFieldNames {
+        const pluralValue = this.plural;
+
+        const pluralValueUpperFirst = upperFirst(pluralValue);
```
Comment (angrykoala) [inline packages/graphql/src/classes/Node.ts:192]: **suggestion** Just to avoid consistency drift between this and `mutationResponseTypeNames` , consider moving this to a separate private function or getter, used by both methods:

```suggestion
        const pascalValue = this.pascal;
```

File: packages/graphql/src/classes/Node.test.ts [hunk 3]
```diff
@@ -62,12 +63,208 @@ describe("Node", () => {
         expect(node.getLabels(defaultContext)).toEqual(["Movie"]);
     });
 
-    test("should return plural with underscores", () => {
-        const node = new NodeBuilder({
-            name: "super_movie",
-        }).instance();
+    describe("root type field names", () => {
```
Comment (angrykoala) [inline packages/graphql/src/classes/Node.test.ts:66]: :clap:

File: packages/graphql/src/schema/make-augmented-schema.ts [hunk 4]
```diff
@@ -923,31 +931,33 @@ function makeAugmentedSchema(
...
+
         if (!node.exclude?.operations.includes("read")) {
             composer.Query.addFields({
-                [node.plural]: findResolver({ node }),
+                [rootTypeFieldNames.read]: findResolver({ node }),
             });
 
             composer.Query.addFields({
-                [`${node.plural}Aggregate`]: aggregateResolver({ node }),
+                [rootTypeFieldNames.aggregate]: aggregateResolver({ node }),
```
Comment (angrykoala) [inline packages/graphql/src/schema/make-augmented-schema.ts:942]: :clap:

File: packages/graphql/src/schema/validation/directives.ts [hunk 5]
```diff
@@ -176,7 +176,7 @@ export const nodeDirective = new GraphQLDirective({
             type: new GraphQLList(new GraphQLNonNull(GraphQLString)),
         },
         plural: {
-            description: "Defines a custom plural for the Node API",
+            description: "Allows for the specification of the plural of the type name if the type name is non-English.",
```
Comment (angrykoala) [inline packages/graphql/src/schema/validation/directives.ts:179]: Great on changing the old description, which is awful in hindsight.
**nitpick** I think there are other cases in which plural directive may be useful, other than non-English typenames.

For instance "Tech" -> "Teches".

```suggestion
            description: "Allows for the specification of the plural of the type name.",
```

File: packages/graphql/tests/integration/issues/235.int.test.ts [hunk 6]
```diff
@@ -64,19 +64,19 @@ describe("https://github.com/neo4j/graphql/issues/235", () => {
 
         const c = generate({ charset: "alphabetic" });
 
-        const createBS = `
+        const createBs = `
             mutation CreateBS($b1: String!, $b2: String!) {
-                createBS(input: [{ name: $b1 }, { name: $b2 }]) {
-                    bS {
+                createBs(input: [{ name: $b1 }, { name: $b2 }]) {
```
Comment (angrykoala) [inline packages/graphql/tests/integration/issues/235.int.test.ts:69]: :rofl:

**Review by angrykoala — DISMISSED** [review]
:+1: A couple of minor non-blocking comments

File: packages/graphql/src/classes/Node.ts (hunk 1 above)
Comment (darrellwarde) [reply packages/graphql/src/classes/Node.ts:145]: I don't believe it's that simple - `match` can be either a `RegExpExecArray` or `null` - so we need some kind of null assertion at some point.

File: packages/graphql/src/classes/Node.test.ts [hunk 7]
```diff
@@ -62,12 +63,208 @@ describe("Node", () => {
...
+            (plural: string, rootTypeFieldNames: RootTypeFieldNames) => {
+                const node = new NodeBuilder({
+                    name: "Test",
+                    nodeDirective: new NodeDirective({ plural }),
+                }).instance();
 
-        expect(node.plural).toBe("super_movies");
+                expect(node.rootTypeFieldNames).toStrictEqual(rootTypeFieldNames);
+            }
+        );
```
Comment (tbwiss) [inline packages/graphql/src/classes/Node.test.ts:267]: question: Is testing the `mutationResponseTypeNames` an overkill? Probably so

**Review by tbwiss — APPROVED** [review]

File: packages/ogm/src/classes/Model.ts [hunk 8]
```diff
@@ -31,25 +28,46 @@ function printSelectionSet(selectionSet: string | DocumentNode | SelectionSetNod
...
+    read: string;
+    update: string;
+    delete: string;
+    aggregate: string;
+};
+
 class Model {
     public name: string;
-    private namePluralized: string;
+    private namePluralized!: string;
```
Comment (angrykoala) [inline packages/ogm/src/classes/Model.ts:41]: :eyes:

**Review by angrykoala — COMMENTED** [review]
All good except the evil exclamations!
