### PR TITLE
Fix: duplicate nodes created if creating following the connection of interface relationships

### LINKED ISSUE #832: Duplicate Nodes Created with Nested 'Connect' when using Interfaces
**Describe the bug**
When using the autogenerated `create` mutations, with `connect` on nested relationship fields - if the type the relationship refers to is an interface rather than type, and you are attempting to create multiple nodes in a single call, spurious duplicate nodes are created.

**Type definitions**

**Note:** This is the same schema that generates another (I think unrelated) bug: https://github.com/neo4j/graphql/issues/847

```gql
interface Entity {
    id: String!
}

type Person implements Entity {
    id   : String! @unique
    name : String!
}

type Place implements Entity {
    id       : String! @unique
    location : Point!
}

type Interaction  {
    id       : ID! @id
    kind     : String!
    subjects : [Entity!]! @relationship(type: "ACTED_IN", direction: IN )
    objects  : [Entity!]! @relationship(type: "ACTED_IN", direction: OUT)
}
```

**To Reproduce**

Run the following mutation against the graphql API using an empty neo4j database:

```graphql
mutation {
  createPeople(input: [
    { id: "adam", name: "Adam" },
    { id: "eve",  name: "Eve" },
    { id: "cain", name: "Cain"},
    { id: "abel", name: "Abel" }, 
  ]) {
    people {
      id
    }
  }
  createInteractions(input: [{
    subjects : { connect: { where: { node: { id_IN: ["adam", "eve"] }}}},
    kind     : "PARENT_OF",
    objects  : { connect: { where: { node: { id_IN: ["cain"] }}}}
  },{
    subjects : { connect: { where: { node: { id_IN: ["adam", "eve"] }}}},
    kind     : "PARENT_OF",
    objects  : { connect: { where: { node: { id_IN: ["abel"] }}}}
  }]) {
    info { nodesCreated }
    interactions { id }
  }
}
```

**Expected behavior**

`createInteractions` should create exactly 2 nodes - instead it creates 3 nodes.

The output `createInterations.interactions` list contains just 2 ID strings - however `info.nodesCreated` is set to 3 - and examining the graph shows indeed that an extra node has been incorrectly created.

Note that if the two nodes are created with 2 separate calls to `createInteractions` (with an input array of length 1 in both cases), the correct behavior is observed. Additionally, modifying the type definitions on the `subjects` and `objects` relationship fields to be `Person` rather than `Entity` results in the correct behavior. Neither of these workarounds should be required.

**Screenshots**

Incorrect resultant graph structure from above mutation:
image

Expected Graph Structure:
image

**System (please complete the following information):**

-   OS: Linux (Debian 10)
-   Version: @neo4j/graphql@2.5.5, graphql@16.2.0, apollo-server@3.6.2
-   Node.js version: v14.15.0
-  Neo4j DB Version: 4.4.0

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

So it turns out that having `UNION` between our connect, update and disconnect operations for interface relationships affects cardinality, which can cause subsequent commands to be executed twice. This simply removed the `UNION`, making them independent subqueries.

# Issue

Closes #832

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at
 http://neo4j-graphql-toolbox-stage-2065.surge.sh (=> for local development; use for instance [Neo4j Desktop](https://neo4j.com/download/))
or
 https://neo4j-graphql-toolbox-stage-2065.surge.sh (=> use to connect to an [Aura Free](https://neo4j.com/cloud/aura-free/) dbms)

File: packages/graphql/src/translate/create-connect-and-params.ts [hunk 1]
```diff
@@ -436,7 +436,7 @@ function createConnectAndParams({
                     res.params = { ...res.params, ...subquery.params };
                 }
             });
-            res.connects.push(subqueries.join("\nUNION\n"));
+            res.connects.push(subqueries.join("\n}\nCALL {"));
```
Comment (tbwiss) [inline packages/graphql/src/translate/create-connect-and-params.ts:439]: question (non-blocking): Why is this not also `\n}\nCALL {\n\t` like in the 'disconnect' and 'update' file?
I also see some tck tests where the `CALL` and `WITH ...` are in the same line rather than the `WITH ...` being on a new line.

**Review by tbwiss — APPROVED** [review]
Just have one comment but apart from that this is good to go IMO!
