### PR TITLE
Fix authorization in create

### LINKED ISSUE #6797: `Variable this0 not defined` on create with authorization
Given a schema with authorization in create operations:

```graphql
type Group @node {
    id: ID! @id
    name: String!
    invitees: [Invitee!]! @relationship(type: "INVITED_TO", direction: IN, aggregate: true)
}

enum InviteeStatus {
    PENDING
    ACCEPTED
}

type Invitee
    @node
    @authorization(
        validate: [
            { operations: [CREATE], where: { node: { group_SINGLE: { inviteesAggregate: { count_LT: 5 } } } } }
        ]
    ) {
    id: ID! @id
    group: [Group!]! @relationship(type: "INVITED_TO", direction: OUT)
    email: String!
    status: InviteeStatus! @default(value: PENDING)
}
```

And a query with a nested create and connect:

```graphql
mutation CreateGroups {
  createGroups(
    input: [
      {
        name: "My Name"
        invitees: {
          create: [
            {
              node: {
                email: "an email"
                group: { connect: [{ where: { node: { id_EQ: "id" } } }] }
              }
            }
          ]
        }
      }
    ]
  ) {
    groups {
      invitees {
        email
      }
    }
  }
}
```
The following Cypher is invalid with the error: `Neo4jError: Variable `this0` not defined (line 30, column 12 (offset: 821))`:
```cypher
CYPHER 5
CALL {
    CREATE (this0:Group)
    SET
        this0.id = randomUUID(),
        this0.name = $param0
    WITH *
    CREATE (this1:Invitee)
    WITH *
    CALL (this1) {
        MATCH (this2:Group)
        WHERE this2.id = $param1
        CREATE (this1)-[this3:INVITED_TO]->(this2)
    }
    MERGE (this0)<-[this4:INVITED_TO]-(this1)
    SET
        this1.id = randomUUID(),
        this1.email = $param2,
        this1.status = $param3
    MATCH (this1)-[:INVITED_TO]->(this5:Group)
    CALL (this5) {
        MATCH (this5)<-[this6:INVITED_TO]-(this7:Invitee)
        RETURN count(this7) < $param4 AS var8
    }
    WITH *
    WHERE var8 = true
    RETURN count(this5) = 1 AS var9
    WITH *
    CALL apoc.util.validate(NOT ($isAuthenticated = true AND var9 = true), "@neo4j/graphql/FORBIDDEN", [0])
    RETURN this0 AS this
}
WITH this
CALL (this) {
    CALL (this) {
        MATCH (this)<-[this10:INVITED_TO]-(this11:Invitee)
        WITH DISTINCT this11
        WITH this11 { .email } AS this11
        RETURN collect(this11) AS var12
    }
    RETURN this { invitees: var12 } AS var13
}
RETURN collect(var13) AS data
```

### PR DESCRIPTION
**Pull request by angrykoala**

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregateWithMultipleFields | 7936 | 7936 | 55 | 79 | 1134 |
|  aggregations.NestedAggregation | 15407 | 15407 | 65 | 95 | 2174 |
|  aggregations.AggregationWithWhere | 10833 | 10833 | 45 | 68 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20097917 | 20097917 | 1939 | 2069 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20097917 | 20097917 | 1958 | 1973 | 2008534 |
|  aggregations.InterfacesAggregations | 8324 | 8324 | 94 | 124 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 13526 | 13526 | 126 | 256 | 2080 |
|  connections.Connection | 12951 | 12951 | 173 | 82 | 2174 |
|  connections.NestedConnection | 37705 | 37705 | 123 | 132 | 4516 |
|  connections.totalCount | 1 | 1 | 17 | 24 | 1 |
|  cypher-directive-mutation.TopLevelMutationDirective | 1135 | 1135 | 24 | 37 | 1134 |
|  cypher-directive.TopLevelSortWithCypher | 12961 | 12961 | 42 | 49 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypher | 12961 | 12961 | 60 | 75 | 2174 |
|  cypher-directive.TopLevelSortWithCypherWithNested | 13096 | 13096 | 61 | 74 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypherWithNested | 13096 | 13096 | 90 | 110 | 2174 |
|  cypher-directive.TopLevelSortWithExpensiveCypher | 13725 | 13725 | 104 | 145 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithExpensiveCypher | 13266 | 13266 | 98 | 167 | 2174 |
|  fulltext.Fulltext | 80 | 80 | 45 | 52 | 16 |
|  fulltext.FulltextWithNestedQuery | 516 | 516 | 62 | 77 | 84 |
|  1262.NestedConnectionWhere | 8703 | 8703 | 51 | 69 | 2174 |
|  187.QueryWhere | 8564 | 8564 | 34 | 47 | 2154 |
|  2871.NestedRelationshipFilter | 19632 | 19632 | 61 | 75 | 4395 |
|  batch-create.BatchCreate | 3600 | 3600 | 91 | 102 | 600 |
|  connect.createAndConnect | 4410 | 4410 | 52 | 68 | 1134 |
|  create.SimpleMutation | 6 | 6 | 32 | 35 | 1 |
|  delete.SimpleDelete | 19401 | 19401 | 686 | 687 | 1040 |
|  delete.NestedDeleteInUpdate | 14688 | 14688 | 108 | 141 | 1179 |
|  update.NestedUpdate | 10129 | 10129 | 61 | 87 | 2002 |
|  query.SimpleQuery | 3121 | 3121 | 22 | 25 | 1040 |
|  query.SimpleQueryWithRelationship | 15031 | 15031 | 48 | 59 | 2174 |
|  query.SimpleQueryWithNestedWhere | 8713 | 8713 | 50 | 66 | 2154 |
|  query.Nested | 3988 | 3988 | 78 | 86 | 1040 |
|  query.OrFilterOnRelationships | 36730 | 36496 | 160 | 185 | 1955 |
|  query.OrFilterOnRelationshipsAndNested | 26719 | 26531 | 210 | 226 | 1955 |
|  query.QueryWithNestedIn | 14192 | 14189 | 56 | 65 | 1864 |
|  query.DeeplyNestedConnectionWhere | 8702 | 8702 | 76 | 95 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 17357 | 17357 | 135 | 165 | 1552 |
|  query.NestedWithRelationshipSingleFilters | 3808 | 3808 | 157 | 213 | 1134 |
|  sorting.SortMultipleTypes | 3436 | 3436 | 78 | 87 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13321 | 13321 | 97 | 121 | 2174 |
|  sorting.SortOnNestedFields | 12951 | 12951 | 49 | 54 | 2174 |
|  sorting.SortDeeplyNestedFields | 39785 | 39785 | 90 | 112 | 4516 |
|  sorting.ConnectionWithSort | 3271 | 3271 | 72 | 79 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 58 | 61 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 56 | 69 | 35 |
|  unions.NestedUnion | 309975 | 309975 | 253 | 274 | 33033 |
|  unions.NestedUnionWithMissingFields | 283949 | 283949 | 254 | 264 | 33033 |

</details>
        
Old Schema Generation: 22.768s
Schema Generation: 22.314s
Old Subgraph Schema Generation: 25.632s
Subgraph Schema Generation: 26.049s

File: packages/graphql/src/translate/queryAST/ast/operations/CreateOperation.ts [hunk 1]
```diff
@@ -181,9 +180,16 @@ export class CreateOperation extends MutationOperation {
...
             }
-            return [...subqueries, new Cypher.With("*").where(predicate), ...selections, ...validations];
+            return [
+                Cypher.utils.concat(
+                    ...subqueries.map((sq) => new Cypher.Call(sq, "*")),
+                    new Cypher.With("*").where(predicate),
+                    ...selections,
+                    ...validations
+                ),
+            ];
```
Comment (a-alle) [inline packages/graphql/src/translate/queryAST/ast/operations/CreateOperation.ts]: thought we concluded there's no selections and predicates for Create auth

File: packages/graphql/src/translate/queryAST/ast/operations/TopLevelCreateMutationOperation.ts [hunk 2]
```diff
@@ -42,36 +42,50 @@ export class TopLevelCreateMutationOperation extends Operation {
...
+        return filterTruthy([...this.topLevelCreateOperations, ...this.projectionOperations]);
     }
 
     public transpile(context: QueryASTContext): OperationTranspileResult {
         if (!context.hasTarget()) {
             throw new Error("No parent node found!");
         }
-        const subqueries = this.createOperations.map((field) => {
-            const { clauses, projectionExpr } = field.transpile(context);
+        const oprationQueries = this.topLevelCreateOperations.map((createOperation) => {
```
Comment (a-alle) [inline packages/graphql/src/translate/queryAST/ast/operations/TopLevelCreateMutationOperation.ts]: typo

**Review by a-alle — DISMISSED** [review]

File: packages/graphql/src/translate/queryAST/ast/operations/CreateOperation.ts (hunk 1 above)
Comment (angrykoala) [reply packages/graphql/src/translate/queryAST/ast/operations/CreateOperation.ts]: Good catch, that was in the other branch and I forgot to port it to this one
