### PR TITLE
Remove incorrect deprecation message from single relationships/connections

### LINKED ISSUE #2890: Incorrect deprecation warning on single relation filters
### Type definitions

```GraphQL
type Movie {
    director: Director! @relationship(type: "HAS_DIRECTOR", direction: OUT)
}

type Director {
    name: String!
}
```

### Test data

_No response_

### Steps to reproduce

Attempt to make the following query:

```gql
query {
  movies(where: { **director:** { name: "" } }) {
    director {
      name
    }
  }
}
```

Note that the director filter is marked as deprecated with the following message: "Use director_SOME instead".

### What happened

The deprecation message does not make sense as there is no director_SOME filter as it is a single relationship. This filter does not exist as only `SINGLE`/`NONE`(currently `director`/`director_NOT`) filters are applicable to single relationships

### Expected behaviour

No deprecation message for the field

### Version

3.16.1

### Database version

5.4

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Liam-Doodson**
# Description

Removed deprecation messages that did not make sense. Created a single source of truth for adding relationship array inputs (`SINGLE`/`ALL`/`NONE`/`SOME`)

## Complexity

Complexity: Low

# Issue

Closes #2890

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2892.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3403 | 3403 | 40 | 59 | 1134 |
|  aggregations.NestedAggregation | 13514 | 13514 | 95 | 125 | 2174 |
|  aggregations.AggregationWithWhere | 10942 | 10942 | 74 | 72 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20101954 | 20101954 | 3178 | 3118 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20101954 | 20101954 | 2914 | 2841 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 8694 | 8694 | 69 | 70 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 8900 | 8900 | 59 | 57 | 2174 |
|  aggregations.DeeplyNestedCount | 10054408 | 10054408 | 4670 | 4473 | 2008534 |
|  batch-create.BatchCreate | 3600 | 3600 | 99 | 135 | 600 |
|  connect.createAndConnect | 12419 | 12419 | 326 | 218 | 3003 |
|  connections.Connection | 13042 | 13042 | 107 | 126 | 2174 |
|  connections.NestedConnection | 33883 | 33883 | 131 | 116 | 4516 |
|  connections.ConnectionWithSort | 2277 | 2277 | 76 | 83 | 1040 |
|  connections.ConnectionWithSortAndCypher | 2277 | 2277 | 198 | 301 | 1040 |
|  create.SimpleMutation | 6 | 6 | 32 | 35 | 1 |
|  cypher-directive.TopLevelCypherDirective | 99525 | 99525 | 774 | 733 | 10168 |
|  cypher-directive.TopLevelCypherDirectiveWithColumnName | 127992 | 127992 | 288 | 359 | 10168 |
|  delete.SimpleDelete | 18361 | 18361 | 249 | 335 | 1040 |
|  delete.NestedDeleteInUpdate | 17123 | 17123 | 158 | 148 | 2040 |
|  query.SimpleQuery | 14120 | 14120 | 93 | 107 | 2174 |
|  query.QueryWhere | 8663 | 8670 | 34 | 40 | 2161 |
|  query.SimpleQueryWithNestedWhere | 8834 | 8841 | 49 | 57 | 2161 |
|  query.Nested | 10084290 | 10084290 | 10287 | 10701 | 2008534 |
|  query.NestedWithFilter | 37172 | 37172 | 118 | 135 | 4511 |
|  query.OrFilterOnRelationships | 34726 | 35197 | 148 | 227 | 1270 |
|  query.OrFilterOnRelationshipsAndNested | 28597 | 28941 | 217 | 273 | 1270 |
|  query.QueryWithNestedIn | 12421 | 12153 | 82 | 63 | 1242 |
|  query.NestedConnectionWhere | 8794 | 8794 | 54 | 83 | 2174 |
|  query.DeeplyNestedConnectionWhere | 8852 | 8844 | 82 | 108 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 6251 | 6251 | 126 | 145 | 1134 |
|  query.NestedWithRelationshipSingleFilters | 3021189 | 3021189 | 626 | 651 | 1003942 |
|  query.Fulltext | 96 | 96 | 25 | 31 | 16 |
|  query.FulltextWithNestedQuery | 571 | 571 | 42 | 58 | 84 |
|  sorting.SortMultipleTypes | 2493 | 2493 | 76 | 77 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 1485 | 1489 | 185 | 277 | 1040 |
|  sorting.SortOnNestedFields | 13042 | 13042 | 63 | 95 | 2174 |
|  sorting.SortDeeplyNestedFields | 38965 | 38965 | 203 | 191 | 4516 |
|  sorting.SortWithTopLevelCypher | 2119 | 2119 | 147 | 214 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 59 | 62 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 57 | 60 | 35 |
|  unions.NestedUnion | 398553 | 398553 | 298 | 308 | 33033 |
|  unions.NestedUnionWithMissingFields | 372527 | 372527 | 289 | 342 | 33033 |
|  update.NestedUpdate | 2119 | 2119 | 55 | 46 | 1040 |

</details>
        
Old Schema Generation: 33.904s
Schema Generation: 34.733s

File: packages/graphql/src/schema/augment/add-relationship-array-filters.ts [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        (["ALL", "NONE", "SINGLE", "SOME"] as const).reduce(
+            (acc, filter) => ({
+                ...acc,
+                [`${fieldName}_${filter}`]: {
+                    type: whereType,
+                    directives: directives,
+                    // e.g. "Return Movies where all of the related Actors match this filter"
+                    description: `Return ${pluralize(sourceName)} where ${
+                        filter !== "SINGLE" ? filter.toLowerCase() : "one"
+                    } of the related ${pluralize(fieldName)} match this filter`,
```
Comment (darrellwarde) [inline packages/graphql/src/schema/augment/add-relationship-array-filters.ts:46]: Rather than the field name, this used to be the related type name, which I think makes more sense for this description. You can see what I mean in the schema tests.

**Review by darrellwarde — CHANGES_REQUESTED** [review]
This looks good, I think the descriptions just need tweaking!

File: packages/graphql/src/schema/augment/add-relationship-array-filters.ts (hunk 1 above)
Comment (Liam-Doodson) [reply packages/graphql/src/schema/augment/add-relationship-array-filters.ts:46]: I actually changed this because I thought it made more sense this way. I saw an example with the following type def:

```gql
type Movie {
    actors: [Person!]! @relationship(...)
    director: Person! @relationship(...)
}
```

Here `people` wouldn't make sense because it could be talking about the actors of the director. I do agree there are examples the other way round that make less sense too. I went this way because it was more specific so there's less room for confusion

Comment (Liam-Doodson) [reply packages/graphql/src/schema/augment/add-relationship-array-filters.ts:46]: I'm happy to change it back if you think it was better before
