### PR TITLE
Remove run first column from nested aggregate where

### LINKED ISSUE #2388: OGM syntax error: The EXISTS subclause is not valid inside a WITH or RETURN clause.
**Describe the bug**
Syntax error when filtering on a property on related node in aggregate.

```
The EXISTS subclause is not valid inside a WITH or RETURN clause. (line 5, column 153 (offset: 437))\n\"RETURN this { partUsagesAggregate: { count: size([(this_partUsagesAggregate_this0:`PartUsage`)-[this_partUsagesAggregate_this2:USAGE_OF]->(this) WHERE (EXISTS {\"\n                                                                                                                                                         ^
```

It creates a query like this
```sql
RUN MATCH (this:`Part`)
WHERE (this.partNumber = $param0 AND apoc.util.validatePredicate(NOT ((any(var1 IN ["upstream"] WHERE any(var0 IN $auth.roles WHERE var0 = var1)) OR any(var3 IN ["downstream"] WHERE any(var2 IN $auth.roles WHERE var2 = var3)))), "@neo4j/graphql/FORBIDDEN", [0]))
RETURN this { partUsagesAggregate: { count: size([(this_partUsagesAggregate_this0:`PartUsage`)-[this_partUsagesAggregate_this2:USAGE_OF]->(this) WHERE (EXISTS {
MATCH (this_partUsagesAggregate_this0)-[:BELONGS_TO]->(this_partUsagesAggregate_this1:`PartAddress`)
WHERE this_partUsagesAggregate_this1.id = $this_partUsagesAggregate_param0
} AND apoc.util.validatePredicate(NOT ((any(auth_var1 IN ["upstream"] WHERE any(auth_var0 IN $auth.roles WHERE auth_var0 = auth_var1)) OR any(auth_var3 IN ["downstream"] WHERE any(auth_var2 IN $auth.roles WHERE auth_var2 = auth_var3)))), "@neo4j/graphql/FORBIDDEN", [0])) | this_partUsagesAggregate_this0]) } } AS this
```

**Type definitions**
```graphql
type PartAddress
@auth(rules: [
    { operations: [READ, CREATE, UPDATE, DELETE, CONNECT, DISCONNECT], roles: ["upstream"] }
    { operations: [READ], roles: ["downstream"] }
])
{
    id: ID! @id
}

type PartUsage
@auth(rules: [
    { operations: [READ, CREATE, UPDATE, DELETE, CONNECT, DISCONNECT], roles: ["upstream"] }
    { operations: [READ], roles: ["downstream"] }
])
{
    partAddress: PartAddress
    @relationship(type: "BELONGS_TO", direction: OUT)
}

type Part
@auth(rules: [
    { operations: [READ, CREATE, UPDATE, DELETE, CONNECT, DISCONNECT], roles: ["upstream"] }
    { operations: [READ], roles: ["downstream"] }
])
{
    partUsages: [PartUsage!]!
    @relationship(type: "USAGE_OF", direction: IN)
}

```

**To Reproduce**
```graphql
query PartByNumber($where: PartWhere) {
  parts(where: $where) {
    partUsagesAggregate(where: {partAddress: {id: "123"}}) {
      count
    }
  }
}
```

**System:**

* Version:
   @neo4j/graphql@3.11.1 @neo4j/graphql-ogm@3.11.1
   @neo4j/graphql@3.12.0 @neo4j/graphql-ogm@3.12.0
* Node.js version: 18.9.0

### LINKED ISSUE #2520: Transaction closed error when using multiple aggregation filters on update mutation on Neo4j 5
**Describe the bug**
Transaction has been closed error on Neo4j 5 when filtering an update by the aggregate of node and edge properties along with a count. This seems to be caused by the transaction from `apoc.runFirstColumn` being closed before the transaction from `apoc.do.when` has completed.

**Type definitions**

```graphql
type User {
    name: String!
    likedPosts: [Post!]! @relationship(type: "LIKES", direction: OUT, properties: "LikesRelationship")
}

type Post {
    id: ID
    content: String!
    likes: [User!]! @relationship(type: "LIKES", direction: IN, properties: "LikesRelationship")
}

interface LikesRelationship {
    likedAt: DateTime
}
```

**To Reproduce**

1. Run a server with the following code:

```javascript
import { ApolloServer, gql } from "apollo-server";
import neo4j from "neo4j-driver";
import { Neo4jGraphQL } from "./index";

const driver = neo4j.driver("bolt://localhost:7687", neo4j.auth.basic("neo4j", "password"));

const typeDefs = gql`
    type User {
        name: String!
        likedPosts: [Post!]! @relationship(type: "LIKES", direction: OUT, properties: "LikesRelationship")
    }

    type Post {
        id: ID
        content: String!
        likes: [User!]! @relationship(type: "LIKES", direction: IN, properties: "LikesRelationship")
    }

    interface LikesRelationship {
        likedAt: DateTime
    }
`;

const neoSchema = new Neo4jGraphQL({
    typeDefs,
    driver,
});

// eslint-disable-next-line @typescript-eslint/no-floating-promises
neoSchema.getSchema().then((schema) => {
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    neoSchema
        .assertIndexesAndConstraints({
            driver,
            options: { create: true },
        })
        .then(() => {
            const server = new ApolloServer({
                schema,
                context: ({ req }) => ({ req }),
            });
            // eslint-disable-next-line @typescript-eslint/no-floating-promises
            server.listen().then(({ url }) => {
                console.log(`🚀 Server ready at ${url}`);
            });
        });
});
```

2. Execute the following Mutation to populate the db:

Operation: 
```graphql
mutation Mutation($input: [UserCreateInput!]!) {
  createUsers(input: $input) {
    users {
      name
      likedPosts {
        id
        content
      }
    }
  }
}
```

Variables:
```json
{
  "input": [
    {
      "name": "userName",
      "likedPosts": {
        "create": [
          {
            "edge": {
              "likedAt": "2022-01-09T18:46:40.000Z"
            },
            "node": {
              "id": "1",
              "content": "An old boring content"
            }
          },
          {
            "edge": {
              "likedAt": "2022-05-01T18:46:40.000Z"
            },
            "node": {
              "id": "2",
              "content": "An old boring content"
            }
          }
        ]
      }
    },
    {
      "name": "userName2",
      "likedPosts": {
        "connect": [
          {
            "where": {
              "node": {
                "id": "2"
              }
            },
            "edge": {
              "likedAt": "2022-08-11T10:06:25.000Z"
            }
          }
        ]
      }
    }
  ]
}
```

4. Then run the following Query:

```graphql
mutation {
    updateUsers(
        where: { name: "userName" }
        update: { 
            likedPosts: {
                where: { 
                    node: {
                        likesAggregate: {
                            edge: {
                                likedAt_LT: "2022-05-01T18:46:40.000Z" 
                            }
                            node: {
                                name_SHORTEST_LT: 10 
                            }
                            count: 1
                        }
                    }
                }
                update: {
                    node: {
                        content: "Exciting new content!"
                    }
                } 
            } 
        }
    ) {
        users {
            name
            likedPosts {
                id
                content
            }
        }
    }
}
```

5. See the following error: `This transaction has already been closed.`

**Expected behavior**
No error.

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@3.13.0
* Node.js version: 16.17.1
* Neo4j 5

### PR DESCRIPTION
**Pull request by Liam-Doodson**
# Description

Performance improvements and bug fixes by removing `runFirstColumn` from aggregation projections and from nested aggregate where filters.

## Complexity

Complexity: Medium

# Issue

Closes #2520 , Closes #2388 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2516.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

File: packages/graphql/src/translate/create-connect-and-params.ts [hunk 1]
```diff
@@ -147,9 +154,12 @@ function createConnectAndParams({
...
                     recursing: true,
                 });
-                if (onTypeNodeWhereAndParams[0]) {
-                    whereStrs.push(onTypeNodeWhereAndParams[0]);
-                    params = { ...params, ...onTypeNodeWhereAndParams[1] };
+                if (onTypeNodeWhereCypher) {
+                    whereStrs.push(onTypeNodeWhereCypher);
+                    params = { ...params, ...onTypeNodeWhereParams };
+                    if (preComputedSubqueries) {
+                        subquery.push(preComputedSubqueries);
```
Comment (Liam-Doodson) [inline packages/graphql/src/translate/create-connect-and-params.ts:161]: Should `aggregateWhere` not be set to true here too?

```suggestion
                        subquery.push(preComputedSubqueries);
                        aggregateWhere = true;
```

File: packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts [hunk 2]
```diff
@@ -17,43 +17,89 @@
...
+    matchPattern: Cypher.Relationship,
+    preComputedWhereFields: Cypher.CompositeClause | undefined,
+    auth: Cypher.Predicate | undefined,
+    wherePredicate: Cypher.Predicate | undefined
+): Cypher.Clause {
+    const matchClause = new Cypher.Match(matchPattern);
+    const whereClause = preComputedWhereFields && !preComputedWhereFields?.empty ? new Cypher.With("*") : matchClause;
+    if (wherePredicate) whereClause.where(wherePredicate);
+    if (auth) whereClause.where(auth);
+    return preComputedWhereFields &&!preComputedWhereFields?.empty
```
Comment (Liam-Doodson) [inline packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts:34]: Missing space 

```suggestion
    return preComputedWhereFields && !preComputedWhereFields?.empty
```

File: packages/graphql/src/translate/translate-top-level-match.ts [hunk 3]
```diff
@@ -182,53 +178,36 @@ function createFulltextMatchClause(
 }
 
 export function preComputedWhereFields(
```
Comment (Liam-Doodson) [inline packages/graphql/src/translate/translate-top-level-match.ts:180]: This should be renamed and moved to somewhere more appropriate

File: packages/graphql/src/translate/where/create-connection-where-and-params.ts [hunk 4]
```diff
@@ -38,11 +38,11 @@ export default function createConnectionWhereAndParams({
     relationship: Relationship;
     relationshipVariable: string;
     parameterPrefix: string;
-}): [string, any] {
+}): [string, string, any] {
```
Comment (angrykoala) [inline packages/graphql/src/translate/where/create-connection-where-and-params.ts:41]: This result signature is confusing. Using `[string, Record<string, any>]` is a relatively common and well-known signature (although not ideal) in our project as it is used widely to refer to Cypher+Params.
However, by adding a 3º element now the signature is increasingly confusing, as the types do not tell you what that middle parameter is

For this case, we should return an object instead, something like:

```suggestion
}): { cypher: string, subquery: string,  params:Record<string, any> } {
```

File: packages/graphql/tests/integration/aggregations/where/mutations/update/update-arg.int.test.ts [hunk 5]
```diff
@@ -257,9 +257,7 @@ describe("Update using aggregate where", () => {
         );
     });
 
-    // TODO: Remove skip when apoc.runFirstColumn removed from aggregate where
-    /* eslint-disable-next-line jest/no-disabled-tests */
-    test.skip("should update when filtering using count, edge and node", async () => {
```
Comment (angrykoala) [inline packages/graphql/tests/integration/aggregations/where/mutations/update/update-arg.int.test.ts:262]: :clap:

**Review by angrykoala — APPROVED** [review]
Looks good, great on moving chunks to cypher-builder. Just a couple of non-important comments

File: packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts [hunk 6]
```diff
@@ -17,43 +17,91 @@
...
+    return new Cypher.RawCypher((env) => {
+        const targetAliasCypher = targetAlias.getCypher(env);
+        const fieldPathCypher = fieldPath.getCypher(env);
+
+        return dedent`${matchWherePattern.getCypher(env)}
+        WITH ${targetAliasCypher} as ${targetAliasCypher}
+        ORDER BY size(${fieldPathCypher}) DESC
+        WITH collect(${fieldPathCypher}) as list
+        RETURN {longest: head(list), shortest: last(list)} AS ${fieldRef.getCypher(env)}`;
+    });
```
[the remark this answers is not in the document]
Comment (Liam-Doodson) [reply packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts:57]: I did consider doing this as part of the PR but I believe not quite all the information required was available within this function.

I agree it should be fairly easy to do at some point in the future though!

**Comment by darrellwarde** [comment]
Let's tidy up all of the changesets into one concise entry! It can be a paragraph long if need be, but it should really be a 1:1 mapping between a changeset entry and a PR IMO.

**Comment by darrellwarde** [comment]
We should be able to remove the `runFirstColumn*` functions as required from `packages/graphql/src/constants.ts`!

**Comment by angrykoala** [comment]
@darrellwarde we cannot remove that as it is still used for `@cypher` without columnName

**Comment by angrykoala** [comment]
> Let's tidy up all of the changesets into one concise entry! It can be a paragraph long if need be, but it should really be a 1:1 mapping between a changeset entry and a PR IMO.

Why?

**Comment by Liam-Doodson** [comment]
> Let's tidy up all of the changesets into one concise entry! It can be a paragraph long if need be, but it should really be a 1:1 mapping between a changeset entry and a PR IMO.

We've mapped the changesets 1:1 with the issues that this closes. It closes 2 github issues and 2 trello cards so that's why we've got 4. Do you still want us to move them all into one?

**Comment by darrellwarde** [comment]
> > We should be able to remove the `runFirstColumn*` functions as required from `packages/graphql/src/constants.ts`!
> 
> @darrellwarde I think we cannot remove that as it is still used for `@cypher` without columnName

... Ignore my insane ramblings.

**Comment by darrellwarde** [comment]
> > Let's tidy up all of the changesets into one concise entry! It can be a paragraph long if need be, but it should really be a 1:1 mapping between a changeset entry and a PR IMO.
> 
> Why?

I dunno, it just feels a bit tidier to me! But I have discussed with Liam, we can leave it as it is.

File: packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts [hunk 7]
```diff
@@ -17,43 +17,91 @@
...
+    const fieldPath = targetAlias.property(fieldName);
+    return new Cypher.RawCypher((env) => {
+        const targetAliasCypher = targetAlias.getCypher(env);
+        const fieldPathCypher = fieldPath.getCypher(env);
+
+        return dedent`${matchWherePattern.getCypher(env)}
+        WITH ${targetAliasCypher} as ${targetAliasCypher}
+        ORDER BY size(${fieldPathCypher}) DESC
+        WITH collect(${fieldPathCypher}) as list
+        RETURN {longest: head(list), shortest: last(list)} AS ${fieldRef.getCypher(env)}`;
```
Comment (darrellwarde) [inline packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts:56]: One style comment and one general question - we don't only return the aggregations from the selection here? We always return `longest` and `shortest` even if only one was asked for?

```suggestion
        RETURN { longest: head(list), shortest: last(list) } AS ${fieldRef.getCypher(env)}`;
```

File: packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts [hunk 8]
```diff
@@ -17,43 +17,91 @@
...
+    fieldName: string,
+    fieldRef: Cypher.Variable,
+    targetAlias: Cypher.Node | Cypher.Relationship
+): Cypher.RawCypher {
+    const fieldPath = targetAlias.property(fieldName);
+    return new Cypher.RawCypher((env) => {
+        const fieldPathCypher = fieldPath.getCypher(env);
+
+        return dedent`${matchWherePattern.getCypher(env)}
+        RETURN {min: min(${fieldPathCypher}), max: max(${fieldPathCypher}), average: avg(${fieldPathCypher}), sum: sum(${fieldPathCypher})}  AS ${fieldRef.getCypher(
```
Comment (darrellwarde) [inline packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts:71]:
```suggestion
        RETURN { min: min(${fieldPathCypher}), max: max(${fieldPathCypher}), average: avg(${fieldPathCypher}), sum: sum(${fieldPathCypher}) }  AS ${fieldRef.getCypher(
```

File: packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts [hunk 9]
```diff
@@ -17,43 +17,91 @@
...
+    fieldName: string,
+    fieldRef: Cypher.Variable,
+    targetAlias: Cypher.Node | Cypher.Relationship
+): Cypher.RawCypher {
+    const fieldPath = targetAlias.property(fieldName);
+    return new Cypher.RawCypher((env) => {
+        const fieldPathCypher = fieldPath.getCypher(env);
+
+        return dedent`${matchWherePattern.getCypher(env)}
+        RETURN {min: min(${fieldPathCypher}), max: max(${fieldPathCypher})} AS ${fieldRef.getCypher(env)}`;
```
Comment (darrellwarde) [inline packages/graphql/src/translate/field-aggregations/aggregation-sub-queries.ts:88]:
```suggestion
        RETURN { min: min(${fieldPathCypher}), max: max(${fieldPathCypher}) } AS ${fieldRef.getCypher(env)}`;
```

**Review by darrellwarde — DISMISSED** [review]
Some fairly unimportant comments given that this has already been reviewed. Looks great, I would just tweak some of the output Cypher a little!

File: packages/graphql/tests/tck/issues/1751.test.ts [hunk 10]
```diff
@@ -84,10 +84,18 @@ describe("https://github.com/neo4j/graphql/issues/1751", () => {
...
-            RETURN count(aggr_node) = $aggr_count
-            \\", { this_admins0: this_admins0, aggr_count: $aggr_count })
+            CALL {
+                WITH this_admins0
+                MATCH (this_deleteOrganizations_args_delete_admins0_where_Adminthis2:\`Organization\`)-[this_deleteOrganizations_args_delete_admins0_where_Adminthis1:HAS_ADMINISTRATOR]->(this_admins0)
+                RETURN count(this_deleteOrganizations_args_delete_admins0_where_Adminthis2) = $this_deleteOrganizations_args_delete_admins0_where_Adminparam0 AS this_deleteOrganizations_args_delete_admins0_where_Adminvar0
+            }
+            WITH *, CASE this_deleteOrganizations_args_delete_admins0_where_Adminvar0 = true
+                WHEN true THEN [ this_admins0_relationship, this_admins0 ]
+                ELSE [ NULL, NULL ]
```
[the remark this answers is not in the document]
Comment (MacondoExpress) [reply packages/graphql/tests/tck/issues/1751.test.ts:94]: It is, in this case, it could be removed by adding `Cypher.Variable` to the `Cypher.Predicate` type, is just not worth in my opinion for the scope of this PR.

File: packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-alias.test.ts [hunk 11]
```diff
@@ -73,11 +73,15 @@ describe("Field Level Aggregations Alias", () => {
...
         expect(formatCypher(result.cypher)).toMatchInlineSnapshot(`
             "MATCH (this:\`Movie\`)
-            RETURN this { actorsAggregate: { node: { myName: head(apoc.cypher.runFirstColumnMany(\\"MATCH (this)<-[r:ACTED_IN]-(n:Actor)
-                    WITH n as n
-                    ORDER BY size(n.name) DESC
-                    WITH collect(n.name) as list
-                    RETURN {longest: head(list), shortest: last(list)}\\", { this: this })) } } } AS this"
+            CALL {
+                WITH this
+                MATCH (this_actorsAggregate_this0:\`Actor\`)-[this_actorsAggregate_this1:ACTED_IN]->(this)
```
[the remark this answers is not in the document]
Comment (MacondoExpress) [reply packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-alias.test.ts:78]: This is how the current pattern is generated by the `Cypher.Relationship`, 
If you have (a)-[]->(b), but you need (a)<-[]-(b), the `Cypher.Relationship` solution is to invert `a` with `b` and maintain the arrow direction LTR which is translated to (b)-[]->(a).

File: packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-alias.test.ts [hunk 12]
```diff
@@ -73,11 +73,15 @@ describe("Field Level Aggregations Alias", () => {
...
+                WITH this_actorsAggregate_this0 as this_actorsAggregate_this0
```
[the remark this answers is not in the document]
Comment (MacondoExpress) [reply packages/graphql/tests/tck/aggregations/field-level-aggregations/field-level-aggregations-alias.test.ts]: nice spot!

**Review by darrellwarde — APPROVED** [review]
