### PR TITLE
Remove _emptyInput from input in resolveTree

### LINKED ISSUE #4838: The `empyInput` flag is ignored during creation.
**Describe the bug**

As my title, if you try to create a node with the emptyInput set a true, the `emptyInput` flag is ignored and instead is written the database.

**Type definitions**

```graphql
type Test {
  test(value: Boolean): Boolean! @cypher(statement: "RETURN $value as value", columnName: "value")
}
```

**To Reproduce**
With the above typeDefs run the below:
```graphql
mutation Mutation {
  createTests(input: { _emptyInput: true }) {
    tests {
      test
    }
  }
}
```

**Expected behavior**
`emptyInput` should not be stored in the `Test` node.

**System (please complete the following information):**

* OS:  macOS
* Version: @neo4j/graphql@5.1.0
* Node.js version: 20.11.0

**Additional context**
Here the Debug log:
**Normal Create**
```cypher
CALL {
WITH [] AS meta
CREATE (this0:Test)
SET this0._emptyInput = $this0__emptyInput
WITH *, meta + { event: "create", id: id(this0), properties: { old: null, new: this0 { .* } }, timestamp: timestamp(), typename: "Test" } AS meta
RETURN this0, meta AS this0_meta
}
WITH this0, this0_meta AS meta
CALL {
    WITH this0
    CALL {
        WITH this0
        CALL {
            WITH this0
            WITH this0 AS this
            RETURN NULL as value
        }
        WITH value AS create_this0
        RETURN create_this0 AS create_var1
    }
    RETURN this0 { test: create_var1 } AS create_var2
}
RETURN [create_var2] AS data, meta
```
**Unwind Create**

```cypher
UNWIND $create_param0 AS create_var0
CALL {
    WITH create_var0
    CREATE (create_this1:Test)
    SET
        create_this1._emptyInput = create_var0._emptyInput
    
    RETURN create_this1
}
CALL {
    WITH create_this1
    CALL {
        WITH create_this1
        WITH create_this1 AS this
        RETURN NULL as value
    }
    WITH value AS create_this2
    RETURN create_this2 AS create_var3
}
RETURN collect(create_this1 { test: create_var3 }) AS data
```

### PR DESCRIPTION
**Pull request by angrykoala**

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3404 | 3404 | 36 | 43 | 1134 |
|  aggregations.TopLevelAggregateWithMultipleFields | 6802 | 6802 | 43 | 63 | 1134 |
|  aggregations.NestedAggregation | 16544 | 16544 | 60 | 71 | 2174 |
|  aggregations.AggregationWithWhere | 11970 | 11970 | 36 | 56 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 22116478 | 22116478 | 2277 | 2405 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 22116478 | 22116478 | 2245 | 2225 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 9701 | 9701 | 32 | 47 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 9928 | 9928 | 37 | 36 | 2174 |
|  aggregations.DeeplyNestedCount | 11062184 | 11062184 | 2943 | 2423 | 2008534 |
|  aggregations.InterfacesAggregations | 6242 | 6242 | 43 | 56 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 11444 | 11444 | 77 | 86 | 2080 |
|  batch-create.BatchCreate | 4200 | 4200 | 119 | 154 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 63 | 68 | 11 |
|  connect.createAndConnect | 14424 | 14424 | 135 | 168 | 3003 |
|  connections.Connection | 14049 | 14049 | 72 | 84 | 2174 |
|  connections.NestedConnection | 41068 | 41068 | 137 | 168 | 4516 |
|  create.SimpleMutation | 7 | 7 | 49 | 56 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 25 | 26 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 193 | 204 | 1040 |
|  delete.NestedDeleteInUpdate | 19165 | 19165 | 142 | 174 | 1980 |
|  2871.NestedRelationshipFilter | 23081 | 23077 | 66 | 56 | 4436 |
|  2925.SingleRelationshipFilter | 6468 | 6468 | 35 | 44 | 1040 |
|  2925.NestedSingleRelationshipFilter | 22891 | 22891 | 65 | 91 | 2174 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 33 | 39 | 1040 |
|  2925.NestedSingleRelationshipRequiredFilter | 9361 | 9361 | 49 | 63 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 17 | 25 | 1040 |
|  query.SimpleQueryWithRelationship | 16129 | 16129 | 38 | 53 | 2174 |
|  query.QueryWhere | 9683 | 9676 | 29 | 43 | 2164 |
|  query.SimpleQueryWithNestedWhere | 9850 | 9843 | 48 | 51 | 2164 |
|  query.Nested | 10095502 | 10095502 | 7048 | 7014 | 2008534 |
|  query.NestedWithFilter | 10074351 | 10074351 | 6976 | 6976 | 2004000 |
|  query.OrFilterOnRelationships | 42410 | 43284 | 131 | 195 | 1672 |
|  query.OrFilterOnRelationshipsAndNested | 36094 | 37618 | 169 | 238 | 1672 |
|  query.QueryWithNestedIn | 13639 | 14010 | 55 | 63 | 1308 |
|  query.NestedConnectionWhere | 9801 | 9801 | 57 | 56 | 2174 |
|  query.DeeplyNestedConnectionWhere | 9860 | 9799 | 64 | 93 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 18800 | 18686 | 110 | 145 | 1598 |
|  query.NestedWithRelationshipSingleFilters | 3865 | 3865 | 139 | 195 | 1134 |
|  query.Fulltext | 64 | 64 | 27 | 35 | 16 |
|  query.FulltextWithNestedQuery | 558 | 558 | 39 | 44 | 84 |
|  sorting-and-cypher.TopLevelSortWithCypher | 14059 | 14059 | 35 | 45 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypher | 14059 | 14059 | 54 | 62 | 2174 |
|  sorting-and-cypher.TopLevelSortWithCypherWithNested | 14204 | 14204 | 54 | 54 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypherWithNested | 14204 | 14204 | 90 | 97 | 2174 |
|  sorting-and-cypher.TopLevelSortWithExpensiveCypher | 14883 | 14883 | 87 | 108 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithExpensiveCypher | 14404 | 14404 | 89 | 99 | 2174 |
|  sorting.SortMultipleTypes | 3498 | 3498 | 76 | 90 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 14504 | 14504 | 91 | 102 | 2174 |
|  sorting.SortOnNestedFields | 14049 | 14049 | 39 | 47 | 2174 |
|  sorting.SortDeeplyNestedFields | 43148 | 43148 | 68 | 86 | 4516 |
|  sorting.ConnectionWithSort | 3281 | 3281 | 67 | 73 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 50 | 56 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 49 | 55 | 35 |
|  unions.NestedUnion | 410637 | 410637 | 231 | 260 | 33033 |
|  unions.NestedUnionWithMissingFields | 384611 | 384611 | 256 | 261 | 33033 |
|  update.NestedUpdate | 16143 | 16143 | 107 | 113 | 2002 |

</details>
        
Old Schema Generation: 26.283s
Schema Generation: 26.388s
Old Subgraph Schema Generation: 29.408s
Subgraph Schema Generation: 30.307s

File: packages/graphql/src/utils/get-neo4j-resolve-tree.ts [hunk 1]
```diff
@@ -50,6 +50,10 @@ function getNeo4jArgumentValue({ argument, type }: { argument: unknown; type: Gr
 
     if (type instanceof GraphQLInputObjectType) {
         return Object.entries(argument as Record<string, unknown>).reduce((res, [key, value]) => {
+            // Ignore meta field _emptyInput
+            if (key === "_emptyInput") {
```
Comment (MacondoExpress) [inline packages/graphql/src/utils/get-neo4j-resolve-tree.ts:54]: smart!

**Review by MacondoExpress — APPROVED** [review]
