### PR TITLE
Fixes the missing takeover of custom directives for interfaces

### LINKED ISSUE #4566: Missing takeover of custom directives for interfaces
**Describe the bug**

Custom directives for interfaces are not take over to augmented interface

**Type definitions**

Given the following schema (from the tests):

https://github.com/neo4j/graphql/blob/9b372bdc65752bcd6a4bf8ea2eb261ac0ddee948/packages/graphql/tests/schema/inheritance.test.ts#L27-L47

The following graphql is augmented:

```graphql
interface Person {
  friends(directed: Boolean = true, options: PersonOptions, where: PersonWhere): [Person!]! @customDirectiveField
  friendsConnection(after: String, directed: Boolean = true, first: Int, sort: [PersonFriendsConnectionSort!], where: PersonFriendsConnectionWhere): PersonFriendsConnection!
  name: String @customDirectiveField
}
```

But i would expect the  `Person` interface to have the directive `@customDirectiveInter` taken over from the source schema

### PR DESCRIPTION
**Pull request by Andy2003**
# Description

Fixes the missing takeover of custom directives for interfaces

## Complexity

Complexity: low

### Closes

closes #4566

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [x] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Thanks for the Neo4j GraphQL Toolbox updates.

The Neo4j GraphQL Toolbox has now been torn down - reopening this PR will republish it.

**Comment by Andy2003** [comment]
I extracted the refactoring part into #4516

File: packages/graphql/src/schema-model/library-directives.ts [hunk 1]
```diff
@@ -17,13 +17,20 @@
...
+import { annotationsParsers } from "./annotation/Annotation";
 import type { DEPRECATED } from "../constants";
 import { SHAREABLE } from "../constants";
 import type { ValueOf } from "../utils/value-of";
 
 const additionalDirectives = ["alias", "relationship", "relationshipProperties", "node", SHAREABLE] as const;
 
 type LibraryDirectives = keyof Annotations | ValueOf<typeof additionalDirectives> | typeof DEPRECATED;
+export const LIBRARY_DIRECTIVES = [
+    ...(Object.keys(annotationsParsers) as LibraryDirectives[])
```
Comment (angrykoala) [inline packages/graphql/src/schema-model/library-directives.ts]: Looks good, my only comment would be to change this type to ` as Array<keyof Annotations>` so it is a bit more accurate

**Review by angrykoala — CHANGES_REQUESTED** [review]

**Review by angrykoala — APPROVED** [review]
