### PR TITLE
Fix #6585

### LINKED ISSUE #6585: changes of #6488 lead to populatedBy directives within node properties not being executed anymore if the node has relations to other nodes and these relations are created within the same mutation which creates the node itself
**Describe the bug**
The callback code for a `populatedBy` directive declared on a node property is not executed anymore if the node has relations to other nodes and these relations are created within the mutation since the changes of https://github.com/neo4j/graphql/pull/6488. With neo4j-graphql @7.2.5 this was working fine.

**Type definitions**
````gql
type CMSContent @mutation(operations: [DELETE,CREATE,UPDATE]) @node @subscription(events: []) {
	changedAt: DateTime @timestamp(operations: [CREATE, UPDATE])
	createdAt: DateTime @timestamp(operations: [CREATE])
	gid: String! @settable(onCreate: true, onUpdate: false)
	organizationUnits: [OrganizationUnit!]! @relationship (type: "CMSCONTENT_BELONGS_TO_ORGANIZATIONUNIT", direction: OUT, nestedOperations: [], queryDirection: DIRECTED) @settable(onCreate: false, onUpdate: false)
	project: [CMSProject!]! @relationship (type: "CMSCONTENT_IS_FOR_CMSPROJECT", properties: "CmscontentIsForCmsprojectProperties", direction: OUT, nestedOperations: [CONNECT, DISCONNECT], queryDirection: DIRECTED) @settable(onCreate: true, onUpdate: false)
	projectId: String! @settable(onCreate: true, onUpdate: false) @populatedBy(callback: "CMSContentProjectIdCallback", operations: [CREATE])
}

type OrganizationUnit @mutation(operations: []) @node @subscription(events: []) {
	abbreviation: String!	
}

type CMSProject @mutation(operations: [UPDATE]) @node @subscription(events: []) {
	changedAt: DateTime @timestamp(operations: [CREATE, UPDATE])
	createdAt: DateTime @timestamp(operations: [CREATE])
	id: String! @settable(onCreate: true, onUpdate: false)
}

type UrlShortcut @mutation(operations: [CREATE,UPDATE,DELETE]) @node @subscription(events: []) {
	changedAt: DateTime @timestamp(operations: [CREATE, UPDATE])
	createdAt: DateTime @timestamp(operations: [CREATE])	
	id: ID! @settable(onCreate: true, onUpdate: false)
	urlPath: String!	
	urlShortcutFamily: [UrlShortcutFamily!]! @relationship (type: "URLSHORTCUTFAMILY_CONSISTS_OF_URLSHORTCUT", properties: "UrlshortcutfamilyConsistsOfUrlshortcutProperties", direction: IN, nestedOperations: [CREATE, UPDATE, DELETE, CONNECT, DISCONNECT], queryDirection: DIRECTED) @settable(onCreate: true, onUpdate: true)
}

type UrlShortcutFamily @mutation(operations: [CREATE,UPDATE,DELETE]) @node @subscription(events: []) {
	changedAt: DateTime @timestamp(operations: [CREATE, UPDATE])
	cmsContent: [CMSContent!]! @relationship (type: "URLSHORTCUTFAMILY_REDIRECTS_TO_CMSCONTENT", properties: "UrlshortcutfamilyRedirectsToCmscontentProperties", direction: OUT, nestedOperations: [CREATE, UPDATE, DELETE, CONNECT, DISCONNECT], queryDirection: DIRECTED) @settable(onCreate: true, onUpdate: true)
	createdAt: DateTime @timestamp(operations: [CREATE])
	id: ID! @settable(onCreate: true, onUpdate: false)
	isActive: Boolean! @default(value: false)
	organizationUnit: [OrganizationUnit!]! @relationship (type: "URLSHORTCUTFAMILY_BELONGS_TO_ORGANIZATIONUNIT", properties: "UrlshortcutfamilyBelongsToOrganizationunitProperties", direction: OUT, nestedOperations: [CONNECT, DISCONNECT], queryDirection: DIRECTED) @settable(onCreate: true, onUpdate: true)
	releasedBy: [ActiveDirectoryUser!]! @relationship (type: "URLSHORTCUTFAMILY_IS_RELEASED_BY_ACTIVEDIRECTORYUSER", properties: "UrlshortcutfamilyIsReleasedByActivedirectoryuserProperties", direction: OUT, nestedOperations: [CONNECT, DISCONNECT], queryDirection: DIRECTED) @settable(onCreate: true, onUpdate: true)
	requestedBy: [ActiveDirectoryUser!]! @relationship (type: "URLSHORTCUTFAMILY_IS_REQUESTED_BY_ACTIVEDIRECTORYUSER", properties: "UrlshortcutfamilyIsRequestedByActivedirectoryuserProperties", direction: OUT, nestedOperations: [CONNECT, DISCONNECT], queryDirection: DIRECTED) @settable(onCreate: true, onUpdate: true)
	urlPath: String!
	urlShortcuts: [UrlShortcut!]! @relationship (type: "URLSHORTCUTFAMILY_CONSISTS_OF_URLSHORTCUT", properties: "UrlshortcutfamilyConsistsOfUrlshortcutProperties", direction: OUT, nestedOperations: [CREATE, UPDATE, DELETE, CONNECT, DISCONNECT], queryDirection: DIRECTED) @settable(onCreate: true, onUpdate: true)
}

type ActiveDirectoryUser @mutation(operations: []) @node(labels: ["ActiveDirectoryUser"]) @subscription(events: []) {
	userName: String!
}

type CmscontentIsForCmsprojectProperties @relationshipProperties {
	_pkFrom: String! @populatedBy(callback: "CMSCONTENT_IS_FOR_CMSPROJECT_OUTGOING_TO_ONE_CONSTRAINT_Callback", operations: [CREATE,UPDATE]) @settable(onCreate: false, onUpdate: false) 
}

type UrlshortcutfamilyConsistsOfUrlshortcutProperties @relationshipProperties {
	_pkTo: String! @populatedBy(callback: "URLSHORTCUTFAMILY_CONSISTS_OF_URLSHORTCUT_INCOMING_TO_ONE_CONSTRAINT_Callback", operations: [CREATE,UPDATE]) @settable(onCreate: false, onUpdate: false) 
}

type UrlshortcutfamilyRedirectsToCmscontentProperties @relationshipProperties {
	_pkFrom: String! @populatedBy(callback: "URLSHORTCUTFAMILY_REDIRECTS_TO_CMSCONTENT_OUTGOING_TO_ONE_CONSTRAINT_Callback", operations: [CREATE,UPDATE]) @settable(onCreate: false, onUpdate: false) 
}

type UrlshortcutfamilyBelongsToOrganizationunitProperties @relationshipProperties {
	_pkFrom: String! @populatedBy(callback: "URLSHORTCUTFAMILY_BELONGS_TO_ORGANIZATIONUNIT_OUTGOING_TO_ONE_CONSTRAINT_Callback", operations: [CREATE,UPDATE]) @settable(onCreate: false, onUpdate: false) 
}

type UrlshortcutfamilyIsReleasedByActivedirectoryuserProperties @relationshipProperties {
	_pkFrom: String! @populatedBy(callback: "URLSHORTCUTFAMILY_IS_RELEASED_BY_ACTIVEDIRECTORYUSER_OUTGOING_TO_ONE_CONSTRAINT_Callback", operations: [CREATE,UPDATE]) @settable(onCreate: false, onUpdate: false) 
}

type UrlshortcutfamilyIsRequestedByActivedirectoryuserProperties @relationshipProperties {
	_pkFrom: String! @populatedBy(callback: "URLSHORTCUTFAMILY_IS_REQUESTED_BY_ACTIVEDIRECTORYUSER_OUTGOING_TO_ONE_CONSTRAINT_Callback", operations: [CREATE,UPDATE]) @settable(onCreate: false, onUpdate: false) 
}
````

**To Reproduce**

1. Run a server with the following code...
2. Execute the following Mutation

````graphql
mutation {
  createUrlShortcutFamilies: createUrlShortcutFamilies(
    input: [
      {
        id: "d10da25b-868b-4f7c-8ea4-72676d63794d"
        isActive: false
        urlPath: "test-create"
        cmsContent: {
          create: [
            {
              node: {
                gid: "ff24ca04-fa99-4d3f-9ef0-4b4a970aa3f7"
                project: {
                  connect: [
                    {
                      where: {
                        node: {
                          id: { eq: "27312f49-02e6-41ad-b754-2c79f53ee9a9" }
                        }
                      }
                    }
                  ]
                }
              }
            }
          ]
        }
        organizationUnit: {
          connect: [{ where: { node: { abbreviation: { eq: "Compl" } } } }]
        }
        requestedBy: {
          connect: [{ where: { node: { userName: { eq: "test" } } } }]
        }
        urlShortcuts: {
          create: [
            {
              node: {
                id: "59e10e44-b152-483a-a4eb-d386a2a0a9cf"
                urlPath: "test-create"
              }
            }
          ]
        }
      }
    ]
  ) {
    info {
      nodesCreated
      relationshipsCreated
    }
  }
}
````

3. The callback for the `populatedBy` directive of the node property `projectId` of node `CMSContent` is not called. The generated cypher does not set the property on the relation (see the `SET` statements for variable `this1`: the property `gid` is being set correctly, but `projectId` is missing):

````cypher
CALL {
    CREATE (this0:UrlShortcutFamily)
    SET
        this0.changedAt = datetime(),
        this0.createdAt = datetime(),
        this0.id = $param0,
        this0.isActive = $param1,
        this0.urlPath = $param2
    WITH *
    CREATE (this1:CMSContent)
    WITH *
    CALL (this1) {
        MATCH (this2:CMSProject)
        WHERE this2.id = $param3
        CREATE (this1)-[this3:CMSCONTENT_IS_FOR_CMSPROJECT]->(this2)
        SET
            this3._pkFrom = $param4
    }
    MERGE (this0)-[this4:URLSHORTCUTFAMILY_REDIRECTS_TO_CMSCONTENT]->(this1)
    SET
        this1.changedAt = datetime(),
        this1.createdAt = datetime(),
        this1.gid = $param5,
        this4._pkFrom = $param6
    WITH *
    CALL (this0) {
        MATCH (this5:OrganizationUnit)
        WHERE this5.abbreviation = $param7
        CREATE (this0)-[this6:URLSHORTCUTFAMILY_BELONGS_TO_ORGANIZATIONUNIT]->(this5)
        SET
            this6._pkFrom = $param8
    }
    WITH *
    CALL (this0) {
        MATCH (this7:ActiveDirectoryUser:MetaActiveDirectoryUser)
        WHERE this7.userName = $param9
        CREATE (this0)-[this8:URLSHORTCUTFAMILY_IS_REQUESTED_BY_ACTIVEDIRECTORYUSER]->(this7)
        SET
            this8._pkFrom = $param10
    }
    WITH *
    CREATE (this9:UrlShortcut)
    MERGE (this0)-[this10:URLSHORTCUTFAMILY_CONSISTS_OF_URLSHORTCUT]->(this9)
    SET
        this9.changedAt = datetime(),
        this9.createdAt = datetime(),
        this9.id = $param11,
        this9.urlPath = $param12,
        this10._pkTo = $param13
    RETURN this0 AS this
}
````

**Expected behavior**
The callback for the `populatedBy` directive of the node property `projectId` of node `CMSContent` should be called as it was before https://github.com/neo4j/graphql/pull/6488. 
By the way: when creating a `CMSContent` node directly, this works fine, e.g. take this mutation:

````graphql
mutation{
  createCmsContents(input:[{
    gid:"test"
    project:{connect:[{where:{node:{id:{eq:"27312f49-02e6-41ad-b754-2c79f53ee9a9"}}}}]}
  }]){
    __typename
  }
}
````

This generates the following cypher with the `projectId` being set:

````cypher
CALL {
    CREATE (this0:CMSContent)
    SET
        this0.changedAt = datetime(),
        this0.createdAt = datetime(),
        this0.gid = $param0,
        this0.projectId = $param1
    WITH *
    CALL (this0) {
        MATCH (this1:CMSProject)
        WHERE this1.id = $param2
        CREATE (this0)-[this2:CMSCONTENT_IS_FOR_CMSPROJECT]->(this1)
        SET
            this2._pkFrom = $param3
    }
    RETURN this0 AS this
}
````

I don't know whether it is due to the nested create or the fact that relationships are created together with the node itself - but the cypher of the upper mutation clearly misses the SET of `projectId` after the relationships are created.

**System (please complete the following information):**

* @neo4j/graphql@7.2.8

### PR DESCRIPTION
**Pull request by angrykoala**
# Description

Fix regression on `@populatedBy` where nested create operations don't trigger callbacks #6585

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregateWithMultipleFields | 7936 | 7936 | 66 | 81 | 1134 |
|  aggregations.NestedAggregation | 15407 | 15407 | 76 | 112 | 2174 |
|  aggregations.AggregationWithWhere | 10833 | 10833 | 50 | 74 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20097917 | 20097917 | 1959 | 2055 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20097917 | 20097917 | 1973 | 1952 | 2008534 |
|  aggregations.InterfacesAggregations | 8324 | 8324 | 110 | 136 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 13526 | 13526 | 136 | 154 | 2080 |
|  connections.Connection | 12951 | 12951 | 67 | 81 | 2174 |
|  connections.NestedConnection | 37705 | 37705 | 136 | 134 | 4516 |
|  connections.totalCount | 1 | 1 | 18 | 20 | 1 |
|  cypher-directive-mutation.TopLevelMutationDirective | 1135 | 1135 | 27 | 29 | 1134 |
|  cypher-directive.TopLevelSortWithCypher | 12961 | 12961 | 48 | 46 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypher | 12961 | 12961 | 63 | 81 | 2174 |
|  cypher-directive.TopLevelSortWithCypherWithNested | 13096 | 13096 | 64 | 90 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypherWithNested | 13096 | 13096 | 103 | 114 | 2174 |
|  cypher-directive.TopLevelSortWithExpensiveCypher | 13725 | 13725 | 116 | 130 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithExpensiveCypher | 13266 | 13266 | 105 | 133 | 2174 |
|  fulltext.Fulltext | 80 | 80 | 51 | 56 | 16 |
|  fulltext.FulltextWithNestedQuery | 516 | 516 | 72 | 77 | 84 |
|  1262.NestedConnectionWhere | 8703 | 8703 | 57 | 67 | 2174 |
|  187.QueryWhere | 8564 | 8564 | 37 | 45 | 2154 |
|  2871.NestedRelationshipFilter | 19632 | 19632 | 58 | 81 | 4395 |
|  batch-create.BatchCreate | 3600 | 3600 | 96 | 109 | 600 |
|  connect.createAndConnect | 4410 | 4410 | 56 | 71 | 1134 |
|  create.SimpleMutation | 6 | 6 | 39 | 33 | 1 |
|  delete.SimpleDelete | 19401 | 19401 | 680 | 670 | 1040 |
|  delete.NestedDeleteInUpdate | 14688 | 14688 | 123 | 142 | 1179 |
|  update.NestedUpdate | 10129 | 10129 | 72 | 73 | 2002 |
|  query.SimpleQuery | 3121 | 3121 | 27 | 27 | 1040 |
|  query.SimpleQueryWithRelationship | 15031 | 15031 | 48 | 49 | 2174 |
|  query.SimpleQueryWithNestedWhere | 8713 | 8713 | 54 | 67 | 2154 |
|  query.Nested | 3988 | 3988 | 79 | 99 | 1040 |
|  query.OrFilterOnRelationships | 36745 | 36724 | 169 | 207 | 1960 |
|  query.OrFilterOnRelationshipsAndNested | 26734 | 26759 | 231 | 234 | 1960 |
|  query.QueryWithNestedIn | 14204 | 14480 | 60 | 62 | 1868 |
|  query.DeeplyNestedConnectionWhere | 8702 | 8702 | 87 | 88 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 17357 | 17357 | 137 | 164 | 1552 |
|  query.NestedWithRelationshipSingleFilters | 3808 | 3808 | 184 | 198 | 1134 |
|  sorting.SortMultipleTypes | 3436 | 3436 | 90 | 91 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13321 | 13321 | 109 | 109 | 2174 |
|  sorting.SortOnNestedFields | 12951 | 12951 | 48 | 56 | 2174 |
|  sorting.SortDeeplyNestedFields | 39785 | 39785 | 93 | 131 | 4516 |
|  sorting.ConnectionWithSort | 3271 | 3271 | 83 | 92 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 70 | 62 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 63 | 65 | 35 |
|  unions.NestedUnion | 309975 | 309975 | 279 | 292 | 33033 |
|  unions.NestedUnionWithMissingFields | 283949 | 283949 | 262 | 289 | 33033 |

</details>
        
Old Schema Generation: 31.359s
Schema Generation: 27.585s
Old Subgraph Schema Generation: 32.721s
Subgraph Schema Generation: 30.223s

File: packages/graphql/src/translate/queryAST/factory/Operations/CreateFactory.ts [hunk 1]
```diff
@@ -470,31 +470,31 @@ export class CreateFactory {
...
+            callbackBucket.addCallback({
+                functionName: callbackFunctionName,
+                param: callbackParam,
+                parent: input,
+                type: attribute.type,
             });
-        } else {
+        });
+
+        if (isNested) {
```
Comment (MacondoExpress) [inline packages/graphql/src/translate/queryAST/factory/Operations/CreateFactory.ts]: I would remove `isNested` from this method and use `relationship` instead.
```suggestion
        if (relationship) {
```

**Review by MacondoExpress — COMMENTED** [review]
LGTM, just left one small comment
