### PR TITLE
Fix `@default` so it works for temporal types and `BigInt` fields

### LINKED ISSUE #5436: Invalid `@default` validation rules
**Describe the bug**

Current `@default` validation does not provide the correct error message for some typeDefs.

For instance:
`Time` issue:
```graphql
type typeNode {
  time: Time @default(value: "10:00:00")
}
```
Raise the following error: "@default.value is not a valid Time" with a correct `Time` value. 
The error in this case should be that `Time` is not supported.

DateTime case:
`DateTime` is a supported type, however, no validation rules happen for a List of `DateTime` values.
```graphql
type typeNode {
  dateTimes: [DateTime] @default(value: ["dummy"])
}
```
The above, in fact, does not raise any error while `dateTime: DateTime @default(value: "dummy")` raise `@default.value is not a valid DateTime`.

Float case:
The `Float` type is supported, however, when not specifying the fraction part it raises an error:
```graphql
type typeNode {
  float: Float @default(value: 1)
}
```
Raise the error: "@default.value on Float fields must be of type Float".
However, this is different from the GraphQL input specification:
https://spec.graphql.org/October2021/#sel-GAHXTHDCAACEB68G

**System (please complete the following information):**

* OS: MacOS
* Version: @neo4j/graphql@5.5.2
* Node.js version: 20

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

Fix `@default` so it works for temporal types and `BigInt` fields

## Complexity

Complexity: Low

# Issue

Closes #5436

### CODE REVIEW

File: packages/graphql/src/schema/validation/custom-rules/directives/default.ts [hunk 1]
```diff
@@ -48,21 +50,38 @@ export function verifyDefault(enums: EnumTypeDefinitionNode[]) {
         }
 
         if (!isArrayType(traversedDef)) {
-            if (isSpatial(expectedType)) {
-                throw new DocumentValidationError(`@default is not supported by Spatial types.`, ["value"]);
-            } else if (isTemporal(expectedType)) {
+            if (["DateTime", "LocalDateTime", "Date"].includes(expectedType)) {
```
Comment (MacondoExpress) [inline packages/graphql/src/schema/validation/custom-rules/directives/default.ts]: Nitpick: IMO `[GraphQLDateTime.name, GraphQLLocalDateTime.name, GraphQLDate.name]`  is better to avoid potential typos.

File: packages/graphql/src/schema/validation/custom-rules/directives/default.ts [hunk 2]
```diff
@@ -48,21 +50,38 @@ export function verifyDefault(enums: EnumTypeDefinitionNode[]) {
...
                 if (Number.isNaN(Date.parse((defaultArg?.value as StringValueNode).value))) {
                     throw new DocumentValidationError(
                         `@default.${defaultArg.name.value} is not a valid ${expectedType}`,
                         ["value"]
                     );
                 }
+            } else if (expectedType == "Time") {
```
Comment (MacondoExpress) [inline packages/graphql/src/schema/validation/custom-rules/directives/default.ts]: Nitpick:
```suggestion
            } else if (expectedType === "Time") {
```

File: packages/graphql/src/schema/validation/custom-rules/directives/default.ts [hunk 3]
```diff
@@ -48,21 +50,38 @@ export function verifyDefault(enums: EnumTypeDefinitionNode[]) {
...
+                try {
+                    parseTime((defaultArg?.value as StringValueNode).value);
+                } catch {
+                    throw new DocumentValidationError(
+                        `@default.${defaultArg.name.value} is not a valid ${expectedType}`,
+                        ["value"]
+                    );
+                }
+            } else if (expectedType == "LocalTime") {
```
Comment (MacondoExpress) [inline packages/graphql/src/schema/validation/custom-rules/directives/default.ts]: Nitpick:
```suggestion
            } else if (expectedType === "LocalTime") {
```

File: packages/graphql/src/schema/validation/custom-rules/directives/default.ts [hunk 4]
```diff
@@ -48,21 +50,38 @@ export function verifyDefault(enums: EnumTypeDefinitionNode[]) {
...
+                    throw new DocumentValidationError(
+                        `@default.${defaultArg.name.value} is not a valid ${expectedType}`,
+                        ["value"]
+                    );
+                }
             } else if (
                 !GRAPHQL_BUILTIN_SCALAR_TYPES.includes(expectedType) &&
-                !enums.some((x) => x.name.value === expectedType)
+                !enums.some((x) => x.name.value === expectedType) &&
+                expectedType != "BigInt"
```
Comment (MacondoExpress) [inline packages/graphql/src/schema/validation/custom-rules/directives/default.ts]: Nitpick: 
```suggestion
                expectedType !== "BigInt"
```

File: packages/graphql/src/schema/validation/validate-document.test.ts [hunk 5]
```diff
@@ -1215,6 +1215,74 @@ describe("validation 2.0", () => {
...
+                    validateDocument({
+                        document: doc,
+                        additionalDefinitions,
+                        features: {},
+                    });
+
+                expect(executeValidate).not.toThrow();
+            });
+
+            test("@default on Time must be valid datetime correct", () => {
```
Comment (MacondoExpress) [inline packages/graphql/src/schema/validation/validate-document.test.ts]: I would change the test titles as they all ending with `must be valid datetime correct`

File: packages/graphql/src/schema/validation/validate-document.test.ts [hunk 6]
```diff
@@ -1215,6 +1215,74 @@ describe("validation 2.0", () => {
...
+                const executeValidate = () =>
+                    validateDocument({
+                        document: doc,
+                        additionalDefinitions,
+                        features: {},
+                    });
+
+                expect(executeValidate).not.toThrow();
+            });
+
```
Comment (MacondoExpress) [inline packages/graphql/src/schema/validation/validate-document.test.ts:1285]: Nitpick: It may worth to add a test with `BigInt` as the other types are tested!

File: packages/graphql/src/schema/get-obj-field-meta.ts [hunk 7]
```diff
@@ -432,6 +432,12 @@ function getObjFieldMeta({
...
                                 primitiveField.defaultValue = parseInt(value.value, 10);
                                 break;
+                            case "BigInt":
+                                if (value?.kind !== Kind.INT && value?.kind !== Kind.STRING) {
+                                    throw new Error(typeError);
+                                }
+                                primitiveField.defaultValue = parseInt(value.value, 10);
+                                break;
                             case "Float":
                                 if (value?.kind !== Kind.FLOAT) {
```
Comment (MacondoExpress) [inline packages/graphql/src/schema/get-obj-field-meta.ts]: Unrelated to this PR, but I believe here we should accept also `INT`
```suggestion
                                if (value?.kind !== Kind.FLOAT || value?.kind !== Kind.INT) {
```

**Review by MacondoExpress — COMMENTED** [review]
LGTM, left some comments!

File: packages/graphql/src/schema/validation/custom-rules/directives/default.ts (hunk 2 above)
Comment (darrellwarde) [reply packages/graphql/src/schema/validation/custom-rules/directives/default.ts]: Too much go 🥲

File: packages/graphql/src/schema/get-obj-field-meta.ts (hunk 7 above)
Comment (darrellwarde) [reply packages/graphql/src/schema/get-obj-field-meta.ts]: Unrelated, but just done and integration test added!
