### PR TITLE
fix: node directive label text is not working (#2614)

### LINKED ISSUE #2614: node directive label text is not working
```
interface Production {
    title: String!
    actors: [Actor!]!
}

type Movie implements Production @node(label:"Film"){
    title: String!
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
    runtime: Int!
}

type Series implements Production {
    title: String!
    actors: [Actor!]! @relationship(type: "ACTED_IN", direction: IN, properties: "ActedIn")
    episodes: Int!
}

interface ActedIn @relationshipProperties {
    role: String!
}

type Actor {
    name: String!
    actedIn: [Production!]! @relationship(type: "ACTED_IN", direction: OUT, properties: "ActedIn")
}

```

```
query GetProductionsMovie {
 actors {
   actedIn (where: { _on: { Movie: {} } }){
      title
   }
 } 
}
```
**Generated Cyper :**
Cypher:
```
MATCH (this:`Actor`)

WITH *
CALL {
WITH *
CALL {
    WITH this
    MATCH (this)-[this0:ACTED_IN]->**_(this_Movie:`Movie`)_**

    RETURN { __resolveType: "Movie", title: this_Movie.title } AS this_actedIn
}
RETURN collect(this_actedIn) AS this_actedIn
}
RETURN this { actedIn: this_actedIn } AS this
```

Why Film label is not used here ? i.e this_Movie:`Film`

### PR DESCRIPTION
**Pull request by tbwiss**
# Description

> **Note**
> 
> Please provide a description of the work completed in this PR below

Use the `getMainLabel()` of the Node class in the interface projection sub-query to get the label provided by the `@node` directive.

## Complexity

> **Note**
>
> Please provide an estimated complexity of this PR of either Low, Medium or High

Complexity: Low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes #2614

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] New files have copyright header

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2631.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

File: packages/graphql/src/translate/create-interface-projection-and-params.ts [hunk 1]
```diff
@@ -121,7 +121,7 @@ function createInterfaceSubquery({
 
     const param = `${nodeVariable}_${refNode.name}`;
     const relatedNode = new Cypher.NamedNode(param, {
-        labels: [refNode.name], // NOTE: should this be labels?
+        labels: [refNode.getMainLabel()],
```
Comment (MacondoExpress) [inline packages/graphql/src/translate/create-interface-projection-and-params.ts:124]: Should not be 
```suggestion
        labels: [refNode.getLabels(context)],
```
instead?

Comment (tbwiss) [reply packages/graphql/src/translate/create-interface-projection-and-params.ts:124]: Yes that's correct. Glad you point this out!

**Review by MacondoExpress — APPROVED** [review]
