### PR TITLE
`queryDirection` fixes

### LINKED ISSUE #5877: Inconsistent behavior of delete operations with undirected relationships
**Describe the bug**

When a relationship has been configured as `UNDIRECTED`/`UNDIRECTED_ONLY`, delete operations nested under a delete operation behave differently to delete operations under an update operation. In this configuration, deletions are performed in an undirected manner, which whilst might sound correct, is inconsistent with all nested operations under update, which behave in a directed manner.

**Type definitions**

```graphql
type User @node {
    name: String!
    friends: [User!]! @relationship(type: "FRIENDS_WITH", direction: OUT, queryDirection: UNDIRECTED)
}
```

### LINKED ISSUE #5878: Behavior of filtering on `DEFAULT_UNDIRECTED` relationship different in Version 6 than Version 5
**Describe the bug**

In Version 5, when filtering on a relationship configured with `DEFAULT_UNDIRECTED`, the `MATCH` is performed in an undirected manner. In Version 6, it is performed in a directed manner, which makes it quite inconsistent.

**Type definitions**

```graphql
type User @node {
    name: String!
    friends: [User!]! @relationship(type: "FRIENDS_WITH", direction: OUT, queryDirection: DEFAULT_UNDIRECTED)
}
```

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

This PR fixes a couple of bugs in how `queryDirection` is interpreted in filtering and mutations.

## Complexity

Complexity: Medium

# Issue

Closes #5877, closes #5878

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregate | 3404 | 3404 | 37 | 48 | 1134 |
|  aggregations.TopLevelAggregateWithMultipleFields | 6802 | 6802 | 46 | 81 | 1134 |
|  aggregations.NestedAggregation | 15407 | 15407 | 59 | 89 | 2174 |
|  aggregations.AggregationWithWhere | 10833 | 10833 | 41 | 73 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20097917 | 20097917 | 1960 | 2170 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20097917 | 20097917 | 1967 | 2001 | 2008534 |
|  aggregations.NestedCountFromMovieToActors | 8603 | 8603 | 37 | 44 | 2174 |
|  aggregations.NestedCountFromActorsToMovie | 8791 | 8791 | 38 | 50 | 2174 |
|  aggregations.DeeplyNestedCount | 10052335 | 10052335 | 2599 | 2639 | 2008534 |
|  aggregations.InterfacesAggregations | 6242 | 6242 | 45 | 54 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 11444 | 11444 | 71 | 88 | 2080 |
|  batch-create.BatchCreate | 4200 | 4200 | 125 | 162 | 600 |
|  batch-create.BatchCreateSmall | 77 | 77 | 53 | 68 | 11 |
|  connect.createAndConnect | 6433 | 6433 | 128 | 173 | 3003 |
|  connections.Connection | 12951 | 12951 | 72 | 75 | 2174 |
|  connections.NestedConnection | 37705 | 37705 | 230 | 169 | 4516 |
|  create.SimpleMutation | 7 | 7 | 51 | 62 | 1 |
|  cypher-directive.TopLevelMutationDirective | 1135 | 1135 | 23 | 28 | 1134 |
|  delete.SimpleDelete | 19401 | 19401 | 680 | 732 | 1040 |
|  2925.SingleRelationshipFilter | 5245 | 5245 | 37 | 58 | 1040 |
|  2925.SingleRelationshipRequiredFilter | 5201 | 5201 | 34 | 50 | 1040 |
|  query.SimpleQuery | 3121 | 3121 | 22 | 29 | 1040 |
|  query.SimpleQueryWithRelationship | 15031 | 15031 | 39 | 52 | 2174 |
|  query.SimpleQueryWithNestedWhere | 8713 | 8713 | 48 | 59 | 2154 |
|  query.Nested | 10084891 | 10084891 | 7149 | 6671 | 2008534 |
|  query.NestedWithFilter | 10064992 | 10064992 | 6329 | 6035 | 2004000 |
|  query.OrFilterOnRelationships | 37378 | 37144 | 146 | 193 | 2171 |
|  query.QueryWithNestedIn | 14900 | 14840 | 56 | 65 | 2100 |
|  query.NestedConnectionWhere | 8703 | 8703 | 51 | 79 | 2174 |
|  query.DeeplyNestedConnectionWhere | 8702 | 8702 | 113 | 98 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 17357 | 17357 | 133 | 174 | 1552 |
|  query.NestedWithRelationshipSingleFilters | 3808 | 3808 | 151 | 210 | 1134 |
|  query.Fulltext | 64 | 64 | 31 | 36 | 16 |
|  query.FulltextWithNestedQuery | 516 | 516 | 44 | 50 | 84 |
|  sorting-and-cypher.TopLevelSortWithCypher | 12961 | 12961 | 46 | 49 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypher | 12961 | 12961 | 65 | 78 | 2174 |
|  sorting-and-cypher.TopLevelSortWithCypherWithNested | 13096 | 13096 | 53 | 59 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithCypherWithNested | 13096 | 13096 | 90 | 110 | 2174 |
|  sorting-and-cypher.TopLevelSortWithExpensiveCypher | 13685 | 13698 | 98 | 138 | 2174 |
|  sorting-and-cypher.TopLevelConnectionSortWithExpensiveCypher | 13266 | 13266 | 105 | 140 | 2174 |
|  sorting.SortMultipleTypes | 3436 | 3436 | 82 | 104 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13321 | 13321 | 107 | 140 | 2174 |
|  sorting.SortOnNestedFields | 12951 | 12951 | 43 | 61 | 2174 |
|  sorting.SortDeeplyNestedFields | 39785 | 39785 | 85 | 105 | 4516 |
|  sorting.ConnectionWithSort | 3271 | 3271 | 74 | 78 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 57 | 65 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 52 | 75 | 35 |
|  unions.NestedUnion | 309975 | 309975 | 274 | 271 | 33033 |
|  unions.NestedUnionWithMissingFields | 283949 | 283949 | 255 | 270 | 33033 |
|  update.NestedUpdate | 14137 | 14137 | 98 | 107 | 2002 |

</details>
        
Old Schema Generation: 27.130s
Schema Generation: 26.180s
Old Subgraph Schema Generation: 26.504s
Subgraph Schema Generation: 27.160s

File: packages/graphql/src/translate/queryAST/ast/selection/RelationshipSelection.ts [hunk 1]
```diff
@@ -81,4 +81,14 @@ export class RelationshipSelection extends EntitySelection {
             selection: match,
         };
     }
+
+    protected getRelationshipDirection(): "left" | "right" | "undirected" {
+        return this.relationship.getCypherDirection(this.directed);
+    }
+}
+
+export class DirectedRelationshipSelection extends RelationshipSelection {
```
Comment (angrykoala) [inline packages/graphql/src/translate/queryAST/ast/selection/RelationshipSelection.ts:91]: It may be worth a comment

```suggestion
/** Enforces direction on the relationship selection, regardless of direction configuration **/
export class DirectedRelationshipSelection extends RelationshipSelection {
```

**Review by angrykoala — DISMISSED** [review]
