### PR TITLE
Fix `@jwtClaims` not working in `@authentication` rules

### LINKED ISSUE #4112: @jwtClaim doesn't seem to add the targeted field to the roles array
# Describe the bug
It seems that `@jwtClaim` is not adding the targeted roles in the roles array, and thus `@authentication` fails to find them. I tested several different setup, but even the one in the doc is failing.

## To Reproduce
All tokens has been generated with jwt.io with the key 123456 , inclued the "admin" role, and are valid for a year.

The server: a classic apollo server with the following
```
const neoSchema = new Neo4jGraphQL({
    typeDefs,
    driver,
    features: {
      authorization: {
        key: "123456", // key used for the test to simplify token generation
      },
    }
  })
```
and lauched with
```
const { url } = await startStandaloneServer(server, {
    listen: { port: 4001 },
    context: async ({ req }) => ({
      token: req.headers.authorization,
    }),
  })
```

the typeDefs is the following:
```
const typeDefs = `#graphql
  type JWT @jwt {
    roles: [String!]!
  }

type Category @authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" } ) {
    name: String! @unique
  }

```

I ran the following tests, every time in order to list the categories, and the expected result here is that it should be ok as the admin role is defined in the jwt:
### "roles" field at the root 
```
type JWT @jwt {
    roles: [String!]!
  }
```

```
@authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" }
```

token used: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTcxMTc2NzIsImV4cCI6MTcyODY1MzgyMSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsInJvbGVzIjpbImFkbWluIl19.jv9vXPuPjsTBLkBcpsQL9wG--N_C898NcHJc0ReWpmI

**Result: OK**

**Map myApplication.roles to roles with jwtClaims (from the doc)**
```
type JWT @jwt {
    roles: [String!]! @jwtClaim(path: "myApplication.roles")
  }
```

```
@authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" }
```

token used: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTcxMTc2NzIsImV4cCI6MTcyODY1MzgyMSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsIm15QXBwbGljYXRpb24iOnsicm9sZXMiOlsiYWRtaW4iXX19.gJsmG0M0BMYWQ9610r6vEVjYBWiAOTGEJnIro-ZhVFQ

**_Result: KO !_**

### Map roles to groups with jwtClaims
That is actually the one I really want to solve, because cognito provide a token with the field `cognito:groups` for the groups at the root. As I cannot define `cognito:groups` as a graphql field, I have to map it.
```
type JWT @jwt {
    roles: [String!]! @jwtClaim(path: "groups")
  }
```

```
@authentication(operations: [READ], jwt: { roles_INCLUDES: "admin" }
```

token used: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE2OTcxMTc2NzIsImV4cCI6MTcyODY1MzgyMSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoianJvY2tldEBleGFtcGxlLmNvbSIsImdyb3VwcyI6WyJhZG1pbiJdfQ.UcZG2NsGBbz0_xDDQcY1T4zufWEAQRpSeLPJqaKbG9U

**_Result: KO !_**

## Conclusion
I ran a lot of other tests, but basically I never managed to have @jwtClaim working as I was expected. So maybe I understand this feature wrong or I am not using it the right way.

## Versions
```
"@apollo/server": "^4.9.4",
"@neo4j/graphql": "^4.3.1",
"apollo-server": "^3.12.1",
"graphql": "^16.8.1",
"neo4j-driver": "^5.13.0"
```

### PR DESCRIPTION
**Pull request by a-alle**
# Description

This PR adds the logic to "expand" a jwt claim with the `@jwtClaims` alias when checking the `@authentication` rules.
Also does this for `@authentication` on top level Cypher fields.
Also does this for `@subscriptionAuthorization` (the claims map was not being provided to `wrapSubscriptions`).
Adds tests for all the above-mentioned cases.

Fixes #4112 

## Complexity

Complexity: Low

# Issue

> **Note**
>
>  Please link to the GitHub issue(s) in which the proposal for this work was discussed
>  
>  To link to multiple issues, use full syntax for each, for example `Closes #1, closes #2, closes #3`

Closes 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

File: packages/graphql/src/translate/authorization/utils/filter-by-values.ts [hunk 1]
```diff
@@ -42,7 +43,13 @@ export function filterByValues<T>(
...
         } else {
             const { fieldName, operator } = parseFilterProperty(k);
-            const receivedValue = receivedValues[fieldName];
+            let receivedValue: T | undefined;
+            const mappedJwtClaim = jwtClaims?.get(fieldName);
+            if (mappedJwtClaim) {
+                receivedValue = expandJwtClaim(mappedJwtClaim, receivedValues);
+            } else {
+                receivedValue = receivedValues[fieldName];
+            }
```
Comment (angrykoala) [inline packages/graphql/src/translate/authorization/utils/filter-by-values.ts:52]: Nitpick

This could be a separate method to get the `receivedValue` from a `fieldName`

File: packages/graphql/src/translate/authorization/utils/filter-by-values.ts [hunk 2]
```diff
@@ -55,3 +62,15 @@ export function filterByValues<T>(
...
+
+function expandJwtClaim<T>(mappedJwtClaim: string, jwtData: Record<string, T>): T | undefined {
+    let receivedValue: T | undefined;
+    let paths = mappedJwtClaim.split(/(?<!\\)\./);
+
+    paths = paths.map((p) => p.replaceAll(/\\\./g, "."));
+
+    for (const p of paths) {
+        receivedValue = (receivedValue || jwtData)[p];
+    }
```
Comment (angrykoala) [inline packages/graphql/src/translate/authorization/utils/filter-by-values.ts:74]: I'm not sure anymore, but I think we used to have an util/lib for this kind of path access operations :thinking:

File: packages/graphql/src/translate/translate-top-level-cypher.ts [hunk 3]
```diff
@@ -52,10 +52,12 @@ export function translateTopLevelCypher({
     if (annotation) {
         applyAuthentication({ context, annotation });
     }
+    // TODO: is this even possible now?
```
Comment (angrykoala) [inline packages/graphql/src/translate/translate-top-level-cypher.ts:55]: What is not possible now? :rofl:

**Review by angrykoala — DISMISSED** [review]

File: .changeset/cold-buttons-glow.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@neo4j/graphql": patch
+---
+
+Fix `@jwtClaims` not working in `@authentication` rules
```
Comment (darrellwarde) [inline .changeset/cold-buttons-glow.md:5]:
```suggestion
Fix `@jwtClaim` not working in `@authentication` rules
```

File: packages/graphql/src/translate/authorization/utils/filter-by-values.ts (hunk 2 above)
Comment (darrellwarde) [reply packages/graphql/src/translate/authorization/utils/filter-by-values.ts:74]: Yeah, why not using `dot-prop` here?

Comment (a-alle) [reply packages/graphql/src/translate/authorization/utils/filter-by-values.ts:74]: oh, yes you're right 🤦‍♀️

File: packages/graphql/src/translate/translate-top-level-cypher.ts (hunk 3 above)
Comment (a-alle) [reply packages/graphql/src/translate/translate-top-level-cypher.ts:55]: because we don't allow `@authorization` directive on top-level cypher fields anymore..

File: packages/graphql/src/translate/authorization/utils/filter-by-values.ts [hunk 5]
```diff
@@ -55,3 +57,23 @@ export function filterByValues<T>(
...
+    const mappedJwtClaim = jwtClaims?.get(fieldName);
+    if (mappedJwtClaim) {
+        return expandJwtClaim(mappedJwtClaim, receivedValues);
+    } else {
+        return receivedValues[fieldName];
+    }
+}
+function expandJwtClaim<T>(mappedJwtClaim: string, jwtData: Record<string, T>): T | undefined {
+    return dotProp.get<T>(jwtData, mappedJwtClaim);
+}
```
Comment (darrellwarde) [inline packages/graphql/src/translate/authorization/utils/filter-by-values.ts:79]: Is this function worthwhile having now it is just a single function call?

**Review by darrellwarde — DISMISSED** [review]
Looks good, just a question about we need the `expandJwtClaim` function now `dot-prop` is used!
