### PR TITLE
Only apply auth update rules if properties values are being updated

### LINKED ISSUE #6620: potential issue with authorization directive when connecting two nodes
**Describe the bug**
To be clear: I don't know whether this is a bug or it is intended. So apologies if I understand the docs wrong.
See these type definitions:

**Type definitions**
````gql
type Car @authorization(filter: [
    {requireAuthentication: false, operations: [READ], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_Car_node_READ"}}}]}}
    {requireAuthentication: false, operations: [AGGREGATE], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_Car_node_AGGREGATE"}}}]}}
    {requireAuthentication: false, operations: [UPDATE], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_Car_node_UPDATE"}}}]}}
    {requireAuthentication: false, operations: [DELETE], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_Car_node_DELETE"}}}]}}
    {requireAuthentication: false, operations: [CREATE_RELATIONSHIP], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_Car_node_CREATE_RELATIONSHIP"}}}]}}
    {requireAuthentication: false, operations: [DELETE_RELATIONSHIP], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_Car_node_DELETE_RELATIONSHIP"}}}]}}
]) @node {
    name: String
    accessibleBy: String
    producedBy: [CarManufacturer!]! @relationship (type: "CAR_IS_PRODUCED_BY_CARMANUFACTURER",  direction: IN,  queryDirection: DIRECTED) 
}

type CarManufacturer @authorization(filter: [
    {requireAuthentication: false, operations: [READ], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_CarManufacturer_node_READ"}}}]}}
    {requireAuthentication: false, operations: [AGGREGATE], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_CarManufacturer_node_AGGREGATE"}}}]}}
    {requireAuthentication: false, operations: [UPDATE], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_CarManufacturer_node_UPDATE"}}}]}}
    {requireAuthentication: false, operations: [DELETE], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_CarManufacturer_node_DELETE"}}}]}}
    {requireAuthentication: false, operations: [CREATE_RELATIONSHIP], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_CarManufacturer_node_CREATE_RELATIONSHIP"}}}]}}
    {requireAuthentication: false, operations: [DELETE_RELATIONSHIP], where: {OR:[{node:{accessibleBy:{eq:null}}}, {node:{accessibleBy:{in:"$jwt.permission_CarManufacturer_node_DELETE_RELATIONSHIP"}}}]}}
]) @node {
    name: String
    accessibleBy: String
}
````

Now insert two nodes:

````cypher
CREATE (car:Car{name:"x1" accessibleBy:"test"})
CREATE (m:CarManufacturer{name:"BMW" accessibleBy:"test"})
````

Then execute the following mutation with a JWT containing the claims `permission_Car_node_CREATE_RELATIONSHIP:test` and `permission_CarManufacturer_node_CREATE_RELATIONSHIP:test`

````graphql
mutation {
  updateCars(
    where: { name: { eq: "x1" } }
    update: {
      producedBy: [{ connect: { where: { node: { name: { eq: "BMW" } } } } }]
    }
  ) {
    info{
      relationshipsCreated
    }
  }
}
````

Zero relationships are created and an error is returned. This is because I do not have the permssion to UPDATE the `Car` node.

So my question on this: Since I do not update any property of `Car` neither of `CarManufacturer` (I just want to CREATE a relationship), shouldn't that work? I mean, yeah, semantically it is an UPDATE mutation on `Car`. But technically the node itself is not touched.
And since there exists the fine-granular differentiation between the `@authorization` operations, I expect to be able to just connect two nodes without the need of having the permission to update one of them.

To be clear: executing this mutation:

````graphql
mutation {
  updateCars(
    where: { name: { eq: "x1" } }
    update: {
      name:{set:"x2"}
      producedBy: [{ connect: { where: { node: { name: { eq: "BMW" } } } } }]
    }
  ) {
    info{
      relationshipsCreated
    }
  }
}
````

should throw an error since in this case the `Car` node is updated. So this works as expected.

**System (please complete the following information):**
* Version: @neo4j/graphql@7.2.10

### PR DESCRIPTION
**Pull request by a-alle**
# Description

Currently auth filter and validate update rules are being applied even if properties are not actually being modified but just relationships are being created or deleted.

## Complexity

Complexity: Low

# Issue

Closes #6620  

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [ ] Documentation has been updated
- [ ] TCK tests have been updated
- [ ] Integration tests have been updated
- [ ] Example applications have been updated
- [ ] New files have copyright header
- [ ] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

File: packages/graphql/src/translate/translate-top-level-match.ts [hunk 1]
```diff
@@ -20,7 +20,7 @@
 import Cypher from "@neo4j/cypher-builder";
```
Comment (angrykoala) [inline packages/graphql/src/translate/translate-top-level-match.ts:20]: This change needs a changeset file

File: packages/graphql/src/translate/translate-top-level-match.ts [hunk 2]
```diff
@@ -74,26 +78,33 @@ function createMatchClause({
     node: Node;
     operation: AuthorizationOperation;
     where: GraphQLWhereArg | undefined;
+    areNodePropertiesBeingUpdated: boolean;
```
Comment (angrykoala) [inline packages/graphql/src/translate/translate-top-level-match.ts]: Because this function is supposed to be more generic than just update, maybe we could rename this flag? something like "ignoreOperationAuthorization"?

File: packages/graphql/src/translate/translate-update.ts [hunk 3]
```diff
@@ -67,13 +67,18 @@ export default async function translateUpdate({
     const matchNode = new Cypher.NamedNode(varName);
     const where = resolveTree.args.where as GraphQLWhereArg | undefined;
     const matchPattern = new Cypher.Pattern(matchNode, { labels: node.getLabels(context) });
+    // bypass auth rules if there's no actual update of properties (connect and disconnect have their own auth rules)
+    const areNodePropertiesBeingUpdated = updateInput
+        ? Object.keys(updateInput).filter((x) => !node.relationFields.some((field) => field.fieldName === x)).length > 0
```
Comment (angrykoala) [inline packages/graphql/src/translate/translate-update.ts]: Is there a reason for not using some in the top level array as well?

```suggestion
        ? Object.keys(updateInput).some((x) => !node.relationFields.some((field) => field.fieldName === x))
```

**Comment by neo4j-team-graphql** [comment]
# Performance Report

No Performance Changes


<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregateWithMultipleFields | 7936 | 7936 | 57 | 80 | 1134 |
|  aggregations.NestedAggregation | 15407 | 15407 | 71 | 106 | 2174 |
|  aggregations.AggregationWithWhere | 10833 | 10833 | 54 | 73 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20097917 | 20097917 | 1945 | 2143 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20097917 | 20097917 | 1957 | 1984 | 2008534 |
|  aggregations.InterfacesAggregations | 8324 | 8324 | 116 | 141 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 13526 | 13526 | 119 | 185 | 2080 |
|  connections.Connection | 12951 | 12951 | 61 | 78 | 2174 |
|  connections.NestedConnection | 37705 | 37705 | 142 | 153 | 4516 |
|  connections.totalCount | 1 | 1 | 45 | 42 | 1 |
|  cypher-directive-mutation.TopLevelMutationDirective | 1135 | 1135 | 50 | 64 | 1134 |
|  cypher-directive.TopLevelSortWithCypher | 12961 | 12961 | 41 | 50 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypher | 12961 | 12961 | 59 | 85 | 2174 |
|  cypher-directive.TopLevelSortWithCypherWithNested | 13096 | 13096 | 58 | 78 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypherWithNested | 13096 | 13096 | 87 | 123 | 2174 |
|  cypher-directive.TopLevelSortWithExpensiveCypher | 13725 | 13725 | 99 | 143 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithExpensiveCypher | 13266 | 13266 | 97 | 122 | 2174 |
|  fulltext.Fulltext | 80 | 80 | 48 | 55 | 16 |
|  fulltext.FulltextWithNestedQuery | 516 | 516 | 65 | 86 | 84 |
|  1262.NestedConnectionWhere | 8703 | 8703 | 55 | 85 | 2174 |
|  187.QueryWhere | 8564 | 8564 | 35 | 53 | 2154 |
|  2871.NestedRelationshipFilter | 19632 | 19632 | 58 | 87 | 4395 |
|  batch-create.BatchCreate | 3600 | 3600 | 85 | 106 | 600 |
|  connect.createAndConnect | 4410 | 4410 | 50 | 68 | 1134 |
|  create.SimpleMutation | 6 | 6 | 31 | 36 | 1 |
|  delete.SimpleDelete | 19401 | 19401 | 697 | 642 | 1040 |
|  delete.NestedDeleteInUpdate | 14688 | 14688 | 111 | 144 | 1179 |
|  update.NestedUpdate | 10129 | 10129 | 72 | 78 | 2002 |
|  query.SimpleQuery | 3121 | 3121 | 29 | 28 | 1040 |
|  query.SimpleQueryWithRelationship | 15031 | 15031 | 60 | 58 | 2174 |
|  query.SimpleQueryWithNestedWhere | 8713 | 8713 | 55 | 79 | 2154 |
|  query.Nested | 3988 | 3988 | 77 | 91 | 1040 |
|  query.OrFilterOnRelationships | 36730 | 36496 | 156 | 207 | 1955 |
|  query.OrFilterOnRelationshipsAndNested | 26719 | 26531 | 204 | 238 | 1955 |
|  query.QueryWithNestedIn | 14192 | 14189 | 57 | 76 | 1864 |
|  query.DeeplyNestedConnectionWhere | 8702 | 8702 | 77 | 109 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 17357 | 17357 | 133 | 180 | 1552 |
|  query.NestedWithRelationshipSingleFilters | 3808 | 3808 | 153 | 218 | 1134 |
|  sorting.SortMultipleTypes | 3436 | 3436 | 83 | 92 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13321 | 13321 | 97 | 105 | 2174 |
|  sorting.SortOnNestedFields | 12951 | 12951 | 49 | 54 | 2174 |
|  sorting.SortDeeplyNestedFields | 39785 | 39785 | 87 | 105 | 4516 |
|  sorting.ConnectionWithSort | 3271 | 3271 | 68 | 74 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 64 | 61 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 60 | 70 | 35 |
|  unions.NestedUnion | 309975 | 309975 | 261 | 305 | 33033 |
|  unions.NestedUnionWithMissingFields | 283949 | 283949 | 258 | 262 | 33033 |

</details>
        
Old Schema Generation: 29.732s
Schema Generation: 28.844s
Old Subgraph Schema Generation: 32.955s
Subgraph Schema Generation: 32.662s

**Review by angrykoala — DISMISSED** [review]

File: packages/graphql/src/translate/translate-update.ts [hunk 4]
```diff
@@ -67,13 +67,18 @@ export default async function translateUpdate({
     const matchNode = new Cypher.NamedNode(varName);
     const where = resolveTree.args.where as GraphQLWhereArg | undefined;
     const matchPattern = new Cypher.Pattern(matchNode, { labels: node.getLabels(context) });
+    // bypass auth rules if there's no actual update of properties (connect and disconnect have their own auth rules)
+    const ignoreOperationAuthorization = updateInput
+        ? !Object.keys(updateInput).some((x) => !node.relationFields.some((field) => field.fieldName === x))
```
Comment (mjfwebb) [inline packages/graphql/src/translate/translate-update.ts]: This line is breaking my brain 🤯 

Is there any way we can remove the negations?

**Review by mjfwebb — APPROVED** [review]
Thank you!
