### PR TITLE
Fix: indexes not being used when filtering on properties of related nodes

### LINKED ISSUE #1628: Filtering on properties of related nodes does not utilise indexes
**Describe the bug**

Reported internally on Trello.

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

Using list predicates (`any()`, etc.) does not trigger the use of indexes for filtering, which makes filtering very slow.

This PR completely changes the filtering against related node properties primarily by trying to use the `EXISTS` clause where it is possible to do so. Where this is not possible, `size()` has been used, but this should be changed when filtering is no longer performed in projections.

# Issue

Closes #1628.

Please find details on internal Trello card.

### CODE REVIEW

File: packages/graphql/src/translate/where/create-where-and-params.ts [hunk 1]
```diff
@@ -227,16 +218,29 @@ function createWhereAndParams({
                     whereInput: entry[1] as any,
                     context,
                     node: refNode,
-                    nodeVariable: `${collectedMap}.node`,
+                    nodeVariable: thisParam,
                     relationship,
-                    relationshipVariable: `${collectedMap}.relationship`,
+                    relationshipVariable: relationshipVariable,
```
Comment (darrellwarde) [inline packages/graphql/src/translate/where/create-where-and-params.ts:223]:
```suggestion
                    relationshipVariable,
```

**Review by tbwiss — COMMENTED** [review]
NIce changes @darrellwarde! Left a few comments to consider

File: packages/graphql/tests/tck/tck-test-files/issues/index-issues.test.ts [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+        const result = await translateQuery(neoSchema, query);
+
+        expect(formatCypher(result.cypher)).toMatchInlineSnapshot(`
+            "MATCH (this:\`frbr__Work\`:\`Resource\`)
+            WHERE EXISTS { (this)-[:dcterms__title]->(this_dcterms__title:\`dcterms_title\`:\`property\`) WHERE this_dcterms__title.value CONTAINS $this_dcterms__title_value_CONTAINS }
+            RETURN this { iri: this.uri, dcterms__title: [ (this)-[:dcterms__title]->(this_dcterms__title:\`dcterms_title\`:\`property\`)  WHERE this_dcterms__title.value CONTAINS $this_dcterms__title_value_CONTAINS | this_dcterms__title { .value } ] } as this
+            LIMIT $this_limit"
+        `);
+    });
```
[the remark this answers is not in the document]
Comment (darrellwarde) [reply packages/graphql/tests/tck/tck-test-files/issues/index-issues.test.ts]: Good spot, thanks!

File: packages/graphql/tests/tck/tck-test-files/advanced-filtering.test.ts [hunk 3]
```diff
@@ -730,12 +730,15 @@ describe("Cypher Advanced Filtering", () => {
...
             expect(formatCypher(result.cypher)).toMatchInlineSnapshot(`
                 "MATCH (this:Movie)
-                WHERE exists((this)-[:IN_GENRE]->(:Genre)) AND any(this_genresConnection_Genre_map IN [(this)-[this_genresConnection_Genre_MovieGenresRelationship:IN_GENRE]->(this_genresConnection_Genre:Genre)  | { node: this_genresConnection_Genre, relationship: this_genresConnection_Genre_MovieGenresRelationship } ] WHERE this_genresConnection_Genre_map.node.name = $this_movies.where.genresConnection.node.name)
+                WHERE size([(this)-[this_genresConnection_Genre_MovieGenresRelationship:IN_GENRE]->(this_genresConnection_Genre:Genre) WHERE this_genresConnection_Genre.name = $this_movies.where.genresConnection.node.name | 1]) > 0
                 RETURN this { .actorCount } as this"
             `);
 
             expect(formatParams(result.params)).toMatchInlineSnapshot(`
                 "{
+                    \\"node\\": {
```
[the remark this answers is not in the document]
Comment (darrellwarde) [reply packages/graphql/tests/tck/tck-test-files/advanced-filtering.test.ts:739]: That is a great spot, I'll look into this tomorrow!

File: packages/graphql/src/translate/where/create-element-where-and-params.ts [hunk 4]
```diff
@@ -110,22 +111,13 @@ function createElementWhereAndParams({
...
 
+                const matchPattern = `(${varName})${inStr}${relTypeStr}${outStr}(${relatedNodeVariable}${labels})`;
+
                 if (value === null) {
-                    res.clauses.push(
-                        `${isNot ? "" : "NOT "}exists((${varName})${inStr}${relTypeStr}${outStr}(:${
-                            relationField.typeMeta.name
-                        }))`
-                    );
+                    res.clauses.push(`${isNot ? "" : "NOT "}EXISTS { ${matchPattern} }`);
```
Comment (angrykoala) [inline packages/graphql/src/translate/where/create-element-where-and-params.ts:117]: Nice

File: packages/graphql/src/translate/where/create-where-and-params.ts [hunk 5]
```diff
@@ -227,16 +218,29 @@ function createWhereAndParams({
...
-                resultStr += connectionWhere[0];
-                resultStr += ")"; // close ALL
-                res.clauses.push(resultStr);
+                if (connectionWhere[0]) {
+                    const clause = listPredicateToSizeFunction(listPredicate, matchPattern, connectionWhere[0]);
+                    res.clauses.push(clause);
+                    res.params = { ...res.params, ...connectionWhere[1] };
+                }
+
+                // TODO: Change to EXISTS when filtering no longer in projection
```
Comment (angrykoala) [inline packages/graphql/src/translate/where/create-where-and-params.ts:234]: **question**
Is it worth keeping this commented code?

File: packages/graphql/src/translate/where/list-predicate-to-clause.ts [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+            clause = `EXISTS { ${matchPattern} WHERE ${where} }`;
+            break;
+        case "none":
+            clause = `NOT EXISTS { ${matchPattern} WHERE ${where} }`;
+            break;
+        case "single":
+            // Sadly no expressive way to check for single match
+            clause = `size([${matchPattern} WHERE ${where} | 1]) = 1`;
+            break;
+        // no default
```
Comment (angrykoala) [inline packages/graphql/src/translate/where/list-predicate-to-clause.ts:41]: Maybe we should add a default with a throw?
Just in case `listPredicate` is not on of the returned values, to have a fast fail

**Review by angrykoala — APPROVED** [review]

File: packages/graphql/src/translate/where/create-where-and-params.ts (hunk 5 above)
Comment (darrellwarde) [reply packages/graphql/src/translate/where/create-where-and-params.ts]: My mistake!

File: packages/graphql/src/translate/where/list-predicate-to-clause.ts (hunk 6 above)
Comment (darrellwarde) [reply packages/graphql/src/translate/where/list-predicate-to-clause.ts:41]: I just really hate doing this because the `ListPredicate` type only specifies these four values - it may as well be a string if we add a default case. I believe this is just an ESLint thing, I would rather have a discussion about the value of the rule.

**Review by tbwiss — APPROVED** [review]

**Comment by jrsperry** [comment]
This is very nice news to me. I had this issue opened a while back where I felt that _NOT (and more modernly _NONE) should return true if that relation doesn't exist. By switching to the EXISTS predicate instead of ANY or NONE on the filter the logic has changed and now would return true if the relationship is empty. 

Here's a link to the original issue: https://github.com/neo4j/graphql/issues/517
