### PR TITLE
Fix #6618

### LINKED ISSUE #6618: Generated cypher for `*Connection` queries with `@limit` directive is highly inperformant and leads to OOM errors
**Describe the bug**
`*Connection` queries are called 6 times and fail with an OOM error if the type has a `@limit` directive and there are lots of nodes in the database.
This is due to generated cypher matches all nodes and collects them, before doing the count.
See these type definitions. We have around 65.000.000 nodes in the database.

**Type definitions**
````gql
type ProductInstance @limit(max: 100, default: 2) {	
	serialNumber: String!	
}
````

**To Reproduce**

1. Insert a massive amount of nodes. I don't know how many it needs. We have 65.000.000
2. Execute the following Query
````graphql
query {
  productInstancesConnection {
    totalCount
  }
}
````
3. See error:

````javascript
2025-09-01T05:32:35.727Z @neo4j/graphql:translate ConnectionReadOperation
|──── NodeSelection
|     |──── NodeSelectionPattern
|──── Pagination <skip: undefined | limit: 2>
2025-09-01T05:32:35.751Z @neo4j/graphql:execution executing cypher
2025-09-01T05:32:35.751Z @neo4j/graphql:execution CYPHER 5
MATCH (this0:ProductInstance)
WITH collect({ node: this0 }) AS edges, count(this0) AS totalCount
CALL (edges) {
    UNWIND edges AS edge
    WITH edge.node AS this0
    WITH *

    LIMIT $param0
    RETURN collect({ node: { __id: id(this0), __resolveType: "ProductInstance" } }) AS var1
}
RETURN { edges: var1, totalCount: totalCount } AS this
2025-09-01T05:32:35.751Z @neo4j/graphql:execution cypher params: {
  param0: Integer { low: 2, high: 0 },
  language: 'en',
  country: '',
  locale: 'en'
}
2025-09-01T05:32:38.942Z @neo4j/graphql:execution executing cypher
2025-09-01T05:32:38.942Z @neo4j/graphql:execution CYPHER 5
MATCH (this0:ProductInstance)
WITH collect({ node: this0 }) AS edges, count(this0) AS totalCount
CALL (edges) {
    UNWIND edges AS edge
    WITH edge.node AS this0
    WITH *

    LIMIT $param0
    RETURN collect({ node: { __id: id(this0), __resolveType: "ProductInstance" } }) AS var1
}
RETURN { edges: var1, totalCount: totalCount } AS this
2025-09-01T05:32:38.942Z @neo4j/graphql:execution cypher params: {
  param0: Integer { low: 2, high: 0 },
  language: 'en',
  country: '',
  locale: 'en'
}
2025-09-01T05:32:42.895Z @neo4j/graphql:execution executing cypher
2025-09-01T05:32:42.895Z @neo4j/graphql:execution CYPHER 5
MATCH (this0:ProductInstance)
WITH collect({ node: this0 }) AS edges, count(this0) AS totalCount
CALL (edges) {
    UNWIND edges AS edge
    WITH edge.node AS this0
    WITH *

    LIMIT $param0
    RETURN collect({ node: { __id: id(this0), __resolveType: "ProductInstance" } }) AS var1
}
RETURN { edges: var1, totalCount: totalCount } AS this
2025-09-01T05:32:42.895Z @neo4j/graphql:execution cypher params: {
  param0: Integer { low: 2, high: 0 },
  language: 'en',
  country: '',
  locale: 'en'
}
2025-09-01T05:32:48.967Z @neo4j/graphql:execution executing cypher
2025-09-01T05:32:48.967Z @neo4j/graphql:execution CYPHER 5
MATCH (this0:ProductInstance)
WITH collect({ node: this0 }) AS edges, count(this0) AS totalCount
CALL (edges) {
    UNWIND edges AS edge
    WITH edge.node AS this0
    WITH *

    LIMIT $param0
    RETURN collect({ node: { __id: id(this0), __resolveType: "ProductInstance" } }) AS var1
}
RETURN { edges: var1, totalCount: totalCount } AS this
2025-09-01T05:32:48.967Z @neo4j/graphql:execution cypher params: {
  param0: Integer { low: 2, high: 0 },
  language: 'en',
  country: '',
  locale: 'en'
}
2025-09-01T05:33:00.322Z @neo4j/graphql:execution executing cypher
2025-09-01T05:33:00.322Z @neo4j/graphql:execution CYPHER 5
MATCH (this0:ProductInstance)
WITH collect({ node: this0 }) AS edges, count(this0) AS totalCount
CALL (edges) {
    UNWIND edges AS edge
    WITH edge.node AS this0
    WITH *

    LIMIT $param0
    RETURN collect({ node: { __id: id(this0), __resolveType: "ProductInstance" } }) AS var1
}
RETURN { edges: var1, totalCount: totalCount } AS this
2025-09-01T05:33:00.322Z @neo4j/graphql:execution cypher params: {
  param0: Integer { low: 2, high: 0 },
  language: 'en',
  country: '',
  locale: 'en'
}
2025-09-01T05:33:18.510Z @neo4j/graphql:execution executing cypher
2025-09-01T05:33:18.510Z @neo4j/graphql:execution CYPHER 5
MATCH (this0:ProductInstance)
WITH collect({ node: this0 }) AS edges, count(this0) AS totalCount
CALL (edges) {
    UNWIND edges AS edge
    WITH edge.node AS this0
    WITH *

    LIMIT $param0
    RETURN collect({ node: { __id: id(this0), __resolveType: "ProductInstance" } }) AS var1
}
RETURN { edges: var1, totalCount: totalCount } AS this
2025-09-01T05:33:18.510Z @neo4j/graphql:execution cypher params: {
  param0: Integer { low: 2, high: 0 },
  language: 'en',
  country: '',
  locale: 'en'
}

````

The query is being executed 6 times. After the last execution, this OOM error raises:

````javascript
Neo4jError: The allocation of an extra 2.0 MiB would use more than the limit 3.5 GiB. Currently using 3.5 GiB. dbms.memory.transaction.total.max threshold reached

    at captureStacktrace (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\result.js:624:17)
    at new Result (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\result.js:112:23)
    at newCompletedResult (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\transaction.js:531:12)
    at Object.run (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\transaction.js:363:20)
    at Transaction.run (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\transaction.js:184:34)
    at ManagedTransaction.run (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\transaction-managed.js:54:21)
    at Executor.transactionRun (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\@neo4j\graphql\src\classes\Executor.ts:282:28)
    at <anonymous> (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\@neo4j\graphql\src\classes\Executor.ts:260:33)
    at TransactionExecutor._safeExecuteTransactionWork (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:211:26)
    at TransactionExecutor.<anonymous> (C:\git\neo4j-graphql-enterprise-server\neo4j-graphql-enterprise-server\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:198:46) {
  constructor: [Function],
  cause: undefined,
  gqlStatus: '51N72',
  gqlStatusDescription: 'error: system configuration or operation exception - memory pool out of memory. Failed to allocate memory in a memory pool. See dbms.memory.transaction.total.max in the neo4j.conf file.',
  diagnosticRecord: [Object],
  classification: 'TRANSIENT_ERROR',
  rawClassification: 'TRANSIENT_ERROR',
  code: 'Neo.TransientError.General.MemoryPoolOutOfMemoryError',
  retriable: true
}
````

**Expected behavior**
The generated cypher should not match all nodes and collect them. We have another type (`Asset`) without a `@limit` directive where this works as expected:

````cypher
MATCH (this0:Asset)
WITH count(this0) AS totalCount
RETURN { totalCount: totalCount } AS this
````

So the generated cypher for the `ProductInstance` type should look like this I guess:

````cypher
MATCH (this0:ProductInstance)
WITH count(this0) AS totalCount
RETURN { totalCount: totalCount } AS this
````

I think there are 2 problems here:
* the generated cypher is wrong and thus highly inperformant
* the cypher is executed multiple times - this should not happen

**System (please complete the following information):**
* Version: @neo4j/graphql@7.2.10

### PR DESCRIPTION
**Pull request by mjfwebb**
# Description

Fixes the case where Connection queries with `@limit` in the type would generate unnecessary cypher with extra node/edge projection.

## Complexity

Low

# Issue

Closes #6618

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
# Performance Report

| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
| 🟩 query.QueryWithNestedIn | 12278 | 14480 | 57 | 81 | 1226 |


🟥 - Performance worsened (dbHits)
🟩 - Performance improved (dbHits)
🟦 - New test
        

<details>
    <summary>Show Full Table</summary>
    
| name | dbHits | old dbHits | time (ms) | old time (ms) | maxRows |
| ---- | ------ | ---------- | --------- | ------------- | ------- |
|  aggregations.TopLevelAggregateWithMultipleFields | 7936 | 7936 | 60 | 68 | 1134 |
|  aggregations.NestedAggregation | 15407 | 15407 | 77 | 95 | 2174 |
|  aggregations.AggregationWithWhere | 10833 | 10833 | 51 | 66 | 2174 |
|  aggregations.AggregationWhereWithinNestedRelationships | 20097917 | 20097917 | 1905 | 2026 | 2008534 |
|  aggregations.AggregationWhereWithinNestedConnections | 20097917 | 20097917 | 1949 | 1960 | 2008534 |
|  aggregations.InterfacesAggregations | 8324 | 8324 | 102 | 127 | 2080 |
|  aggregations.InterfacesAggregationsWithTwoFields | 13526 | 13526 | 122 | 157 | 2080 |
|  connections.Connection | 12951 | 12951 | 62 | 77 | 2174 |
|  connections.NestedConnection | 37705 | 37705 | 129 | 145 | 4516 |
|  connections.totalCount | 1 | 1 | 18 | 22 | 1 |
|  cypher-directive-mutation.TopLevelMutationDirective | 1135 | 1135 | 28 | 35 | 1134 |
|  cypher-directive.TopLevelSortWithCypher | 12961 | 12961 | 48 | 57 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypher | 12961 | 12961 | 65 | 82 | 2174 |
|  cypher-directive.TopLevelSortWithCypherWithNested | 13096 | 13096 | 61 | 76 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithCypherWithNested | 13096 | 13096 | 93 | 121 | 2174 |
|  cypher-directive.TopLevelSortWithExpensiveCypher | 13650 | 13725 | 116 | 143 | 2174 |
|  cypher-directive.TopLevelConnectionSortWithExpensiveCypher | 13266 | 13266 | 106 | 120 | 2174 |
|  fulltext.Fulltext | 80 | 80 | 50 | 54 | 16 |
|  fulltext.FulltextWithNestedQuery | 516 | 516 | 72 | 75 | 84 |
|  1262.NestedConnectionWhere | 8703 | 8703 | 53 | 68 | 2174 |
|  187.QueryWhere | 8564 | 8564 | 38 | 47 | 2154 |
|  2871.NestedRelationshipFilter | 19632 | 19632 | 59 | 69 | 4395 |
|  batch-create.BatchCreate | 3600 | 3600 | 90 | 102 | 600 |
|  connect.createAndConnect | 4410 | 4410 | 54 | 58 | 1134 |
|  create.SimpleMutation | 6 | 6 | 35 | 33 | 1 |
|  delete.SimpleDelete | 19401 | 19401 | 629 | 638 | 1040 |
|  delete.NestedDeleteInUpdate | 14688 | 14688 | 114 | 167 | 1938 |
|  update.NestedUpdate | 10129 | 10129 | 61 | 81 | 2002 |
|  query.SimpleQuery | 3121 | 3121 | 24 | 27 | 1040 |
|  query.SimpleQueryWithRelationship | 15031 | 15031 | 46 | 56 | 2174 |
|  query.SimpleQueryWithNestedWhere | 8713 | 8713 | 51 | 74 | 2154 |
|  query.Nested | 3988 | 3988 | 76 | 88 | 1040 |
|  query.OrFilterOnRelationships | 34756 | 36724 | 176 | 213 | 1297 |
|  query.OrFilterOnRelationshipsAndNested | 24745 | 26759 | 204 | 243 | 1297 |
| 🟩 query.QueryWithNestedIn | 12278 | 14480 | 57 | 81 | 1226 |
|  query.DeeplyNestedConnectionWhere | 8702 | 8702 | 74 | 97 | 2174 |
|  query.DeeplyNestedWithRelationshipFilters | 17357 | 17357 | 132 | 155 | 1552 |
|  query.NestedWithRelationshipSingleFilters | 3808 | 3808 | 151 | 210 | 1134 |
|  sorting.SortMultipleTypes | 3436 | 3436 | 79 | 91 | 1040 |
|  sorting.SortMultipleTypesWithCypherWithCypher | 13321 | 13321 | 96 | 118 | 2174 |
|  sorting.SortOnNestedFields | 12951 | 12951 | 45 | 64 | 2174 |
|  sorting.SortDeeplyNestedFields | 39785 | 39785 | 87 | 122 | 4516 |
|  sorting.ConnectionWithSort | 3271 | 3271 | 70 | 86 | 1040 |
|  unions.SimpleUnionQuery | 321 | 321 | 60 | 63 | 35 |
|  unions.SimpleUnionQueryWithMissingFields | 293 | 293 | 55 | 65 | 35 |
|  unions.NestedUnion | 309975 | 309975 | 267 | 275 | 33033 |
|  unions.NestedUnionWithMissingFields | 283949 | 283949 | 255 | 280 | 33033 |

</details>
        
Old Schema Generation: 28.157s
Schema Generation: 28.645s
Old Subgraph Schema Generation: 30.587s
Subgraph Schema Generation: 32.049s

File: packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts [hunk 1]
```diff
@@ -465,6 +465,15 @@ export class ConnectionFactory {
 
         operation.setHasTotalCount(Boolean(totalCount || pageInfo));
 
+        // TODO: This should probably be set as an edgeField instead
+        // This is an edge-case where the client requests only the cursor field on the edge
+        const selectedEdgeCursor = findFieldsByNameInFieldsByTypeNameField(resolveTreeEdgeFields, "cursor").length > 0;
+
+        // If the client requested pageInfo or edge cursor, the operation needs to project edges so page cursors can be computed. Otherwise, avoid projecting edges.
+        if (pageInfo || selectedEdgeCursor) {
```
Comment (luffy1727) [inline packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts:472]: wouldn't it be better to be explicit and check `pageInfo !== null || selectedEdgeCursor !== null`

Comment (mjfwebb) [reply packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts:472]: In this particular case, neither of these values can be `null`:

`const pageInfo: ResolveTree | undefined`

`const selectedEdgeCursor: boolean`

We also tend not to do explicit type checks when we can rely on boolean truthiness/falsiness.

File: packages/graphql/tests/tck/connections/projections/projections.test.ts [hunk 2]
```diff
@@ -159,10 +159,15 @@ describe("Relay Cursor Connection projections", () => {
...
+                WITH collect({ node: this1, relationship: this0 }) AS edges, count(this1) AS totalCount
+                CALL (edges) {
+                    UNWIND edges AS edge
+                    WITH edge.node AS this1, edge.relationship AS this0
+                    RETURN collect({ node: { __id: id(this1), __resolveType: \\"Actor\\" } }) AS var2
+                }
+                RETURN { edges: var2, totalCount: totalCount } AS var3
             }
-            RETURN this { .title, actorsConnection: var2 } AS this"
+            RETURN this { .title, actorsConnection: var3 } AS this"
```
Comment (angrykoala) [inline packages/graphql/tests/tck/connections/projections/projections.test.ts:170]: I'm not sure why this has changed, as it does seem to be the opposite of what the issue is about. Was this another separate bug?

File: packages/graphql/tests/tck/connections/alias.test.ts [hunk 3]
```diff
@@ -141,4 +141,136 @@ describe("Connections Alias", () => {
             }"
         `);
     });
+
+    test("should alias startCursor", async () => {
```
Comment (angrykoala) [inline packages/graphql/tests/tck/connections/alias.test.ts]: Should these be tck tests?

All of these aliases are done in JS, which means that the cypher itself is unchanged. 

These seem to be present in the file `alias.int.test.ts`, any reason for adding them here?

File: packages/graphql/tests/tck/issues/6618.test.ts [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+        const query = /* GraphQL */ `
+            query {
+                productInstancesConnection {
+                    totalCount
+                }
+            }
+        `;
+
+        const result = await translateQuery(neoSchema, query);
+
```
Comment (angrykoala) [inline packages/graphql/tests/tck/issues/6618.test.ts:50]: This looks good, but I'm wondering if it is worth making a more explicit check, as this issue is specifically about the generated Cypher. Maybe checking that the cypher does not contain "LIMIT"?

This is not standard practice in our TCK tests, so I'm not too opinionated in adding it, but I feel this and the integration tests don't really validate the issue is fixed :/

File: packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts (hunk 1 above)
Comment (angrykoala) [reply packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts:472]: For more context, by convention we do not use null in this project (except some cases where we need it to interface with GraphQL or other tools), we only use undefined to try and keep our sanity

File: packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts [hunk 5]
```diff
@@ -465,6 +465,15 @@ export class ConnectionFactory {
 
         operation.setHasTotalCount(Boolean(totalCount || pageInfo));
 
+        // TODO: This should probably be set as an edgeField instead
```
Comment (angrykoala) [inline packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts]: If I'm not mistaken, the cursor is calculated in JS, so it is probably better to keep it outside of the queryAST

**Review by angrykoala — CHANGES_REQUESTED** [review]

File: .changeset/five-carpets-count.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+---
+"@neo4j/graphql": patch
+---
+
+Fixes the case where Connection queries with @limit in the type would generate unnecessary cypher with extra node/edge projection.
```
Comment (angrykoala) [inline .changeset/five-carpets-count.md]:
```suggestion
Fixes the case where Connection queries with `@limit` in the type would generate unnecessary cypher with extra node/edge projection.
```

We want to avoid pinging this GitHub user :smile:

File: packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts (hunk 5 above)
Comment (mjfwebb) [reply packages/graphql/src/translate/queryAST/factory/Operations/ConnectionFactory.ts]: Agreed

File: packages/graphql/tests/tck/connections/projections/projections.test.ts (hunk 2 above)
Comment (mjfwebb) [reply packages/graphql/tests/tck/connections/projections/projections.test.ts:170]: Will also add an integration test and changelog

File: packages/graphql/tests/tck/connections/alias.test.ts (hunk 3 above)
Comment (mjfwebb) [reply packages/graphql/tests/tck/connections/alias.test.ts]: Will move these to integration tests

File: packages/graphql/tests/tck/issues/6618.test.ts (hunk 4 above)
Comment (mjfwebb) [reply packages/graphql/tests/tck/issues/6618.test.ts:50]: Will add an assert for the explicit lack of the collect

**Review by angrykoala — APPROVED** [review]
