### PR TITLE
Fix/2474

### LINKED ISSUE #2474: Cannot read properties of undefined (reading 'relationFields')
**Describe the bug**

Experienced whilst trying to insert test data reported in #2396.

**Type definitions**

```gql
type PostalCode @exclude(operations: [DELETE]) {
  archivedAt: DateTime
  number: String! @id(autogenerate: false)

  address: [Address!]! @relationship(type: "HAS_POSTAL_CODE", direction: IN)
}

union AddressNode = Estate

type Address @exclude(operations: [DELETE]) {
  archivedAt: DateTime
  uuid: ID! @id
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])

  postalCode: PostalCode! @relationship(type: "HAS_POSTAL_CODE", direction: OUT)

  node: [AddressNode!]! @relationship(type: "HAS_ADDRESS", direction: IN)
}

type Mandate @exclude(operations: [DELETE]) {
  archivedAt: DateTime
  number: ID! @id # numéro
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])

  price: Float!

  valuation: Valuation! @relationship(type: "HAS_VALUATION", direction: OUT)
}

type Valuation @exclude(operations: [DELETE]) {
  archivedAt: DateTime
  uuid: ID! @id
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])

  estate: Estate @relationship(type: "VALUATION_FOR", direction: OUT)
}

enum EstateType {
  APARTMENT
  HOUSE_VILLA
  TOWNHOUSE
  LAND
  PARKING
  BOX
  BUILDING
  COMMERCIAL_PREMISE
  CHALET
  CASTLE
  OFFICE
  BUSINESS_FUND
}

type Estate @exclude(operations: [DELETE]) {
  archivedAt: DateTime
  uuid: ID! @id
  createdAt: DateTime! @timestamp(operations: [CREATE])
  updatedAt: DateTime! @timestamp(operations: [CREATE, UPDATE])

  estateType: EstateType!
  area: Float!
  floor: Int

  address: Address @relationship(type: "HAS_ADDRESS", direction: OUT)
}
```

**To Reproduce**

Use GraphQL Toolbox with the type definitions above. Run the following Mutation:

```gql
mutation {
  createMandates(
    input: [
      {
        price: 99000
        valuation: {
          create: {
            node: {
              estate: {
                create: {
                  node: {
                    address: {
                      create: {
                        node: {
                          postalCode: { create: { node: { number: "13001" } } }
                        }
                      }
                    }
                    area: 75
                    estateType: APARTMENT
                    floor: 2
                  }
                }
              }
            }
          }
        }
      }
    ]
  ) {
    info {
      nodesCreated
    }
  }
}

```

Receive the error.

**Expected behavior**

For the data to be created.

### PR DESCRIPTION
**Pull request by MacondoExpress**
# Fix for bug 2474

Having a relationField named node does not produce anymore an error in the unwind-create context

Closes 

#2474 

# Checklist

The following requirements should have been met (depending on the changes in the branch):

- [x] Documentation has been updated
- [x] TCK tests have been updated
- [x] Integration tests have been updated
- [x] Example applications have been updated
- [x] New files have copyright header
- [x] CLA (https://neo4j.com/developer/cla/) has been signed

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-stage-2501.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

File: packages/graphql/src/translate/batch-create/parser.ts [hunk 1]
```diff
@@ -35,15 +35,18 @@ function getRelationshipFields(
...
+     /*    if (relationField.union) {
             Object.keys(value as Record<string, any>).forEach((unionTypeName) => {
                 refNodes.push(context.nodes.find((x) => x.name === unionTypeName) as Node);
             });
         } else if (relationField.interface) {
             relationField.interface?.implementations?.forEach((implementationName) => {
                 refNodes.push(context.nodes.find((x) => x.name === implementationName) as Node);
             });
-        } else {
+        } */ else {
```
Comment (darrellwarde) [inline packages/graphql/src/translate/batch-create/parser.ts:49]: What is the purpose of leaving this commented code here?

**Review by darrellwarde — APPROVED** [review]
Looks good once we solve the mystery of the commented code!

File: packages/graphql/src/translate/batch-create/parser.ts (hunk 1 above)
Comment (MacondoExpress) [reply packages/graphql/src/translate/batch-create/parser.ts]: It's the correct parser for the interfaces/unions with the unwind-create but because is not implemented yet and we raise an error before it will became an unreachable code with `relationField.interface/relationField.union` be of type `never`.
But I removed it and keep track of this in another branch!

Comment (darrellwarde) [reply packages/graphql/src/translate/batch-create/parser.ts]: Sounds good!
