### PR TITLE
Fix 1536

### LINKED ISSUE #1536: Something with interfaces generates invalid cypher
**Describe the bug**
I'm not sure what actually triggers this error, but it triggers given the following schema

**Type definitions**
```graphql
type SomeNode {
    id: ID! @id
    other: OtherNode! @relationship(type: "HAS_OTHER_NODES", direction: OUT)
}

type OtherNode {
    id: ID! @id
    interfaceField: MyInterface! @relationship(type: "HAS_INTERFACE_NODES", direction: OUT)
}

interface MyInterface {
    id: ID! @id
}

type MyImplementation implements MyInterface {
    id: ID! @id
}
```

**To Reproduce**
Run the following query:

```graphql
query {
  someNodes {
    id
    other {
      interfaceField {
        id
      }
    }
  }
}
```
and you should get an error, similar to #1535 

```
Variable `interfaceField` not defined (line 2, column 117 (offset: 138))\n\"RETURN this { .id, other: head([ (this)-[:HAS_OTHER_NODES]->(this_other:OtherNode)   | this_other { interfaceField: interfaceField } ]) } as this\"\n                                                                                                                     ^
```

**System (please complete the following information):**

* OS: macOS
* Version: @neo4j/graphql@3.2.0
* Node.js version: [e.g. 14.16.0]14

### PR DESCRIPTION
**Pull request by angrykoala**
# Description

This PR fixes #1536 by adding the interface subqueries into the projection subquery flow

### CODE REVIEW

File: packages/graphql/src/translate/cypher-builder/clauses/Match.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ export class Match<T extends MatchableElement = any> extends Clause {
     }
 }
 
-export interface Match extends WithReturn, WithWhere, WithSet, WithWith {}
+export interface Match<T extends MatchableElement> extends WithReturn, WithWhere, WithSet, WithWith {}
```
Comment (tbwiss) [inline packages/graphql/src/translate/cypher-builder/clauses/Match.ts:89]: question: Are all these CypherBuilder updates suppose to be part of this PR?

File: packages/graphql/src/translate/cypher-builder/utils/utils.test.ts [hunk 2]
```diff
@@ -46,8 +46,17 @@ describe("CypherBuilder Utils", () => {
             ["Spring Data Neo4j⚡️RX", "`Spring Data Neo4j⚡️RX`"],
             ["Foo \u0060", "`Foo ```"], // This is the backtick itself in the string
             ["Foo \\u0060", "`Foo ```"], // This is the backtick unicode escaped so that without further processing `foo \u0060` would end up at Cypher
+            ["Foo``bar", "`Foo````bar`"],
```
Comment (tbwiss) [inline packages/graphql/src/translate/cypher-builder/utils/utils.test.ts:49]: question: Yes this shouldn't be part of this PR right?

**Comment by neo4j-team-graphql** [comment]
Made some changes to the GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at
 http://neo4j-graphql-toolbox-stage-2009.surge.sh (=> for local development; use for instance [Neo4j Desktop](https://neo4j.com/download/))
or
 https://neo4j-graphql-toolbox-stage-2009.surge.sh (=> use to connect to an [Aura Free](https://neo4j.com/cloud/aura-free/) dbms)

File: packages/graphql/tests/integration/issues/1536.int.test.ts [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+            }
+
+            type MyImplementation implements MyInterface {
+                id: ID! @id
+            }
+        `;
+
+        const session = await neo4j.getSession();
+
+        // await session.run(`
```
Comment (tbwiss) [inline packages/graphql/tests/integration/issues/1536.int.test.ts:66]: question: can we remove this?

File: packages/graphql/tests/integration/issues/1536.int.test.ts [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+                            id
+                        }
+                    }
+                }
+            }
+        `;
+
+        const queryResult = await graphqlQuery(query);
+        expect(queryResult.errors).toBeUndefined();
+        console.log(queryResult.data);
```
Comment (tbwiss) [inline packages/graphql/tests/integration/issues/1536.int.test.ts:94]: Same here, maybe just check for the existence of `someNodes`

File: packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/implementation-allow.test.ts [hunk 5]
```diff
@@ -256,7 +256,8 @@ describe("@auth allow on specific interface implementation", () => {
             YIELD value AS _
             RETURN count(*) AS _
             }
-            WITH this
+            WITH *
```
Comment (tbwiss) [inline packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/implementation-allow.test.ts:259]: Hmm, two times `WITH *`?

File: packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/interface-allow.test.ts [hunk 6]
```diff
@@ -276,7 +276,8 @@ describe("@auth allow with interface relationships", () => {
             YIELD value AS _
             RETURN count(*) AS _
             }
-            WITH this
+            WITH *
```
Comment (tbwiss) [inline packages/graphql/tests/tck/tck-test-files/directives/auth/arguments/allow/interface-relationships/interface-allow.test.ts:279]: Double `WITH *` again.
Just wondering if it's a problem

File: packages/graphql/tests/tck/tck-test-files/interface-relationships/create/connect.test.ts [hunk 7]
```diff
@@ -94,52 +94,52 @@ describe("Interface Relationships - Create connect", () => {
...
-                WITH this0
-                MATCH (this0)-[:ACTED_IN]->(this0_Series:Series)
-                RETURN { __resolveType: \\"Series\\", episodes: this0_Series.episodes, title: this0_Series.title } AS actedIn
-            }
-            RETURN collect(actedIn) AS actedIn
-            }
-            RETURN [
-            this0 { .name, actedIn: actedIn }] AS data"
-        `);
+"CALL {
```
Comment (tbwiss) [inline packages/graphql/tests/tck/tck-test-files/interface-relationships/create/connect.test.ts:97]: question: How come the indentation is suddenly changed?

File: packages/graphql/tests/tck/tck-test-files/interface-relationships/update/create.test.ts [hunk 8]
```diff
@@ -89,29 +89,29 @@ describe("Interface Relationships - Update create", () => {
...
-            RETURN collect(DISTINCT this { .name, actedIn: actedIn }) AS data"
-        `);
+"MATCH (this:\`Actor\`)
+CREATE (this_create_actedIn_Movie0_node_Movie:Movie)
+SET this_create_actedIn_Movie0_node_Movie.title = $this_create_actedIn_Movie0_node_Movie_title
+SET this_create_actedIn_Movie0_node_Movie.runtime = $this_create_actedIn_Movie0_node_Movie_runtime
+MERGE (this)-[this_create_actedIn_Movie0_relationship:ACTED_IN]->(this_create_actedIn_Movie0_node_Movie)
+SET this_create_actedIn_Movie0_relationship.screenTime = $this_create_actedIn_Movie0_relationship_screenTime
+WITH *
+WITH *
```
Comment (tbwiss) [inline packages/graphql/tests/tck/tck-test-files/interface-relationships/update/create.test.ts:99]: Double `WITH *`

File: packages/graphql/tests/tck/tck-test-files/issues/1536.test.ts [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+                id: ID! @id
+            }
+        `;
+
+        neoSchema = new Neo4jGraphQL({
+            typeDefs,
+        });
+    });
+
+    test("should use alias in result projection for a field using an interface", async () => {
```
Comment (tbwiss) [inline packages/graphql/tests/tck/tck-test-files/issues/1536.test.ts:55]: We may have to update this description

File: packages/graphql/tests/tck/tck-test-files/issues/1536.test.ts [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+        `;
+        const result = await translateQuery(neoSchema, query);
+
+        expect(formatCypher(result.cypher)).toMatchInlineSnapshot(`
+"MATCH (this:\`SomeNode\`)
+CALL {
+    WITH this
+    MATCH (this)-[thisthis0:HAS_OTHER_NODES]->(this_other:\`OtherNode\`)
+    WITH this_other
+    CALL {
```
Comment (tbwiss) [inline packages/graphql/tests/tck/tck-test-files/issues/1536.test.ts:76]: 👏

File: packages/graphql/src/translate/cypher-builder/clauses/Clause.ts [hunk 11]
```diff
@@ -21,8 +21,9 @@ import { CypherASTNode } from "../CypherASTNode";
 import { CypherEnvironment, EnvPrefix } from "../Environment";
 import type { CypherResult } from "../types";
 
-/** Represents a clause ast node */
+/** Represents a clause AST node */
```
Comment (tbwiss) [inline packages/graphql/src/translate/cypher-builder/clauses/Clause.ts:24]: question: Should these CypherBuilder updates be part of this PR?

**Review by tbwiss — COMMENTED** [review]
Great fix @angrykoala!
Found some things that we may need to fix.

File: packages/graphql/tests/tck/tck-test-files/interface-relationships/update/create.test.ts (hunk 8 above)
Comment (angrykoala) [reply packages/graphql/tests/tck/tck-test-files/interface-relationships/update/create.test.ts:99]: There is not much we can do about this until we fully refactor this I'm afraid :confused:

File: packages/graphql/tests/tck/tck-test-files/interface-relationships/create/connect.test.ts (hunk 7 above)
Comment (angrykoala) [reply packages/graphql/tests/tck/tck-test-files/interface-relationships/create/connect.test.ts:97]: This is a common problem with jest snapshots when the version of jest is not up to date (not sure why). I'll fix these in the PR

File: packages/graphql/tests/tck/tck-test-files/interface-relationships/update/create.test.ts (hunk 8 above)
Comment (tbwiss) [reply packages/graphql/tests/tck/tck-test-files/interface-relationships/update/create.test.ts]: Sure!

File: packages/graphql/tests/integration/issues/1536.int.test.ts [hunk 12]
```diff
@@ -0,0 +1,114 @@
...
+ */
+
+import type { GraphQLSchema } from "graphql";
+import { graphql } from "graphql";
+import type { Driver, Session } from "neo4j-driver";
+import Neo4j from "../neo4j";
+import { Neo4jGraphQL } from "../../../src";
+import { generateUniqueType } from "../../utils/graphql-types";
+
+describe("https://github.com/neo4j/graphql/issues/1536", () => {
```
Comment (tbwiss) [inline packages/graphql/tests/integration/issues/1536.int.test.ts:27]: 🚀

**Review by tbwiss — APPROVED** [review]
Nice one @angrykoala!
