### PR TITLE
Fix: `cypherParams` in context now work as expected when using OGM

### LINKED ISSUE #3773: Cypher Directives containing $jwt.sub are not working when called over OGM in Beta
**Describe the bug**
In the new Beta Iam not able to call a cypher that contains a $jwt.sub over the OGM.

This is a bit related to #3772 because I think before the auth was injected globally 

I have a custom resolver that creates something over the OGM and has a cypher with $jwt in the selection set.
It seems like auth is not global anymore. So when I use the OGM to create something and the selection set has a cypher with $jwt.sub in it, I get @neo4j/graphql:execute Neo4jError: Expected parameter(s): jwt because the executed call to neo4j does not contain the jwt in the params.

I tried adding the jwt to the args or context of the OGM Model but that does not help.

Example types
```
type Event {
  userAttending: Boolean!
    @cypher(
      statement: """
      MATCH (user:User {id: $jwt.sub})-[:ATTENDS]->(this)
      RETURN COUNT(user) <> 0 as result
      """
      columnName: "result"
    )

  organisation: Organisation
    @relationship(type: "ORGANISATION_OF_EVENT", direction: OUT)
}


type Organisation {
  id: ID!
  name: String!
  events: [Event!]! @relationship(type: "ORGANISATION_OF_EVENT", direction: IN)
}




```

Example OGM call
```
  const Organisation = context.ogm.model("Organisation");

  const [organisation] = await Organisation.create({
    args: {
      jwt: context.jwt, //This is sadly also not working to add jwt to the neo4j execution params
    },
    selectionSet: `
    {
      organisations {
      __typename
      id
      name
      events {
        id
        name
        userAttending
      }
    }
  }
    `,
    input: {
      name: args.name,
    },
    context: context,
  })
    .then((resp: any) => {
      console.log(resp);
      return resp.organisations;
    })
    .catch(async (e: any) => console.log(e));
  console.log("Success: Created Organisation " + organisation.id);
```

Logs
```
Params:
{
  "this0_name": "test",
  "resolvedCallbacks": {}
} +22s
  @neo4j/graphql:execute Neo4jError: Expected parameter(s): jwt

    at captureStacktrace (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\result.js:611:17)
    at new Result (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\result.js:105:23)
    at newCompletedResult (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\transaction.js:506:12)
    at Object.run (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\transaction.js:338:20)
    at Transaction.run (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\transaction.js:179:34)
    at ManagedTransaction.run (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\transaction-managed.js:56:21)
    at Executor.transactionRun (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Executor.js:152:28)
    at C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql\dist\classes\Executor.js:138:33
    at TransactionExecutor._safeExecuteTransactionWork (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:141:26)
    at TransactionExecutor.<anonymous> (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:128:46)
    at step (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:52:23)
    at Object.next (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:33:53)
    at fulfilled (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\neo4j-driver-core\lib\internal\transaction-executor.js:24:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  constructor: [Function],
  code: 'Neo.ClientError.Statement.ParameterMissing',
  retriable: false
} +2s
Error: Expected parameter(s): jwt
    at Model.create (C:\Projekte\Dashpoint\dashpoint-graphql-backend\node_modules\@neo4j\graphql-ogm\dist\classes\Model.js:127:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Expected behavior**
Global jwt injection into the Neo4J Params or the possibility to add things like the jwt into the execution params when calling the OGM Model function like

```
  const [organisation] = await Organisation.create({
    additionalParams: {
      jwt: context.jwt, // Added to neo4j cypher params
    },
    selectionSet: `
    {
      organisations {
      __typename
      id
      name
      events {
        id
        name
        userAttending
      }
    }
  }
    `,
    input: {
      name: args.name,
    },
    context: context,
  })
```

### PR DESCRIPTION
**Pull request by darrellwarde**
# Description

This PR moves the inclusion of `cypherParams` into the database executor, removing the need to inject these during translation. These extra parameters were not being added in all cases, resulting in this unexpected behaviour.

## Complexity

Complexity: Low

# Issue

Closes #3773

### CODE REVIEW

**Comment by neo4j-team-graphql** [comment]
Made some changes to the Neo4j GraphQL Toolbox? Or made some changes to the core library perhaps?

Check out your changes at https://neo4j-graphql-toolbox-3830.surge.sh

Use for instance a local dbms hosted on [Neo4j Desktop](https://neo4j.com/download/) or a cloud-hosted [Aura Free](https://neo4j.com/cloud/aura-free/) dbms.

File: packages/graphql/src/classes/Executor.ts [hunk 1]
```diff
@@ -82,6 +82,7 @@ export type ExecutorConstructorParam = {
     executionContext: ExecutionContext;
     cypherQueryOptions?: CypherQueryOptions;
     sessionConfig?: SessionConfig;
+    cypherParams?: Record<string, any>;
```
Comment (angrykoala) [inline packages/graphql/src/classes/Executor.ts:85]: Does this need to be `Record<string, any>`? Could `Record<string, unknown>` work here?

File: packages/graphql/src/translate/translate-read.ts [hunk 2]
```diff
@@ -192,7 +192,7 @@ export function translateRead(
         projectionSubqueries,
         projectionClause
     );
-    const result = readQuery.build(undefined, context.cypherParams ? { ...context.cypherParams } : {});
+    const result = readQuery.build();
```
Comment (angrykoala) [inline packages/graphql/src/translate/translate-read.ts:195]: this bit here is lovely

**Review by angrykoala — APPROVED** [review]
